apache/myfaces

api/src/main/java/javax/faces/component/_UIWebsocket.java
api/src/main/resources/META-INF/componentClass20.vm
impl/src/main/java/org/apache/myfaces/push/WebsocketComponentRenderer.java

https://issues.apache.org/jira/browse/MYFACES-4232

MYFACES-4232 Update UIWebsocket signature in the JSF 2.3 API

---

impl/src/main/java/org/apache/myfaces/context/PartialResponseWriterImpl.java
impl/src/main/java/org/apache/myfaces/util/IllegalXmlCharacterFilterWriter.java
impl/src/test/java/org/apache/myfaces/context/PartialResponseWriterImplTest.java

Fixes
- https://issues.apache.org/jira/browse/MYFACES-4266
Related to
- https://github.com/primefaces/primefaces/issues/3875
@tandraschko Could you please check that and - if accepted - merge it to the other branches as well?

MYFACES-4266: Ajax update fails due to invalid characters in response XML (DoS)

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

see https://issues.apache.org/jira/browse/MYFACES-4273

MYFACES-4273 close() JarFile in Classpath

---

impl/src/test/resources/org/apache/myfaces/view/facelets/stateless/stateless.xhtml
impl/src/test/resources/org/apache/myfaces/view/facelets/stateless/template.xhtml

Without this I get a failure when trying to perform a new release:
[INFO] [ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project myfaces-impl: Too many files with unapproved license: 2 See RAT report in:

Add missing license to test files

---

parent/pom.xml
pom.xml

The master pom here https://github.com/apache/myfaces-master-pom/blob/master/pom.xml lists 2.2.1 and we are getting failures in the myfaces core when trying to do a release: 
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2.1:attached (make_assembly_src) on project myfaces-core-assembly: Failed to create assembly: Error creating assembly archive coresrc: posix is not a legal value for this attribute -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2.1:attached (make_assembly_src) on project myfaces-core-assembly: Failed to create

Update MavenReleasePlugin version to 2.5.4

---

impl/src/test/java/org/apache/myfaces/cdi/bean/CDIGenericConverterValidatorTest.java
impl/src/test/java/org/apache/myfaces/cdi/bean/CustomConverter.java
impl/src/test/java/org/apache/myfaces/cdi/bean/CustomValidator.java
impl/src/test/resources/org/apache/myfaces/cdi/bean/CDIGenericConverterTest.xhtml
impl/src/test/resources/org/apache/myfaces/cdi/bean/CDIGenericValidatorTest.xhtml

Added two unit tests to ensure that the generic converter & validator work as expected.
And let me know if there are any issues. Particularly, I'm not sure if I should implement testValidator another way.  I kept it simple with the try catch, but I can use some JUnit feature to expect a FacesException if recommended. 
Tested issue:
https://issues.apache.org/jira/browse/MYFACES-4311
https://github.com/apache/myfaces/pull/75

Myfaces 4311 Unit Tests

---

api/pom.xml
parent/pom.xml
pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

README.md
extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/showcase/README.md
extensions/quarkus/showcase/pom.xml
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/InputController.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/LazySorter.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/LazyView.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MethodHandleELResolverBean.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MyBacking.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MyValidator.java
extensions/quarkus/showcase/src/main/resources/application.properties
extensions/quarkus/showcase/src/test/java/org/apache/myfaces/core/extensions/quarkus/showcase/QuarkusMyFacesNativeIT.java
extensions/quarkus/showcase/src/test/java/org/apache/myfaces/core/extensions/quarkus/showcase/QuarkusMyFacesShowcaseTest.java

* Enable native mode
* Adds tests on showcase module (jvm and native)
We still miss an automatic way to [register JSF managed beans](https://github.com/rmpestano/myfaces/blob/2fe17af334422284aa9362307535ecf91b2a447e/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java#L622) for reflection

Quarkus native mode support

---

shared/src/main/java/org/apache/myfaces/shared/resource/ResourceLoaderUtils.java

We conduct an issue that our resources have incorrect header: `Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT`.
After investigating the issue, I found that we deploy using Tomcat with a version tag and a path to resources contains special characters (`#`).
And this method can not read the resources, because the URL (file path) contains URL Encoded characters (for OS this is not a valid path) like this: `/some-path/tomcat/webapps/v3%23%233.2.1/resources/layout/js/layout.js`.
I'm not sure if this PR is the best solution. But it solves this issue for us.
Now I created a custom implementation of ResourceHalder and Resource (just a copy of myfaces impls) to update the method and fix this issue. It would be good if you can release a fix, or give a hint on how to patch it easier.

Incorrect Last-Modified header for resources

---

impl/pom.xml
impl/src/main/java/org/apache/myfaces/util/IllegalXmlCharacterFilterWriter.java

1) Update the Animal Sniffer Plugin to the latest version as the old version was not working correctly with the `@IgnoreJRERequirement` annotation. 
2) Add the `animal-sniffer-annotations` as a dependency so we can compile with `@IgnoreJRERequirment`
3) Add `@IgnoreJRERequirement` to the methods that use `isSurrogate`

Animal sniffer plugin updates and ignores

---

assembly/pom.xml

During my last attempt at a 2.2.13 release the release rollback did not return the assembly/pom.xml back to its original state.
This needs to be fixed before trying a 2.2.13 release again.
Doing a comparison between these three commits I think everything will be good once this is merged:
1. https://github.com/apache/myfaces/commit/bc8234438a19816befc2093867e6adf6f2257f3d
2. https://github.com/apache/myfaces/commit/e36407e900e6bc602553b414e3de8a27c883d67e
3. https://github.com/apache/myfaces/commit/2387543c1fc0b77a6493eb2c7f258b6bb4ca3b9d

Rollback assembly pom

---

assembly/pom.xml

Tried another release and my local tags were out of sync with the remote tags so it failed since there was already a `myfaces-core-module-2.2.13` tag in my local repository. The tag is deleted  on the 2.2.x remote branch.
I've deleted it locally as well now and things look good. I got in a bad state with the release so I had to perform a `mvn release:rollback` but that seems to always miss the assembly/pom file updates and needs to be done manually.
Initial release commit this go around: https://github.com/apache/myfaces/commit/d811bdbd5b89c5dc6e471b0fa8329b215b52df08
rollback: https://github.com/apache/myfaces/commit/14a3300cc713f862fda65445b3df4d9d6938ef8d
Should be good to try again once this is merged.

Roll back assembly pom to 2.2.13-SNAPSHOT

---

api/pom.xml
api/src/main/java/javax/faces/component/UIInput.java
impl-test/src/main/java/org/apache/myfaces/mc/test/core/AbstractMyFacesTestCase.java
impl-test/src/main/java/org/apache/myfaces/mc/test/core/runner/AbstractJsfTestContainer.java
impl/pom.xml
parent/pom.xml

When I was building the site for the 2.2.13 release I ran into a number of problems since we're using git now. It was necessary to update the parent pom to 19 locally to get the 2.2.13 tag site to build properly and deployed.
Updating here so we don't have the issue going forward on the next 2.2.x release. However in order to make this change for compilation there were a number of new check styles and the poms/files had to be updated to resolve these issues.
This PR contains all the necessary changes.
1) Update pom version from 16 to 19.
2) Update check style issues found when updating number 1.
3) Updated to use 2.17 version of maven-checkstyle-plugin to be consistent with 2.3/master
4) Add period to javadoc for:
```
@JSFWebConfigParam(defaultValue="false", expectedValues="true, false", …
```

Update parent pom to 19

---

impl/src/main/java/org/apache/myfaces/context/servlet/StartupServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/webapp/ManagedBeanDestroyerListener.java

Allow an `HttpSession` to be set on `StartupServletExternalContextImpl` so that `javax.faces.bean.ViewScoped` cleanup can work correctly in `DefaultViewScopeProvider`
For https://issues.apache.org/jira/browse/MYFACES-4353

MYFACES-4353 javax.faces.bean.ViewScoped cleanup 2.3.x

---

impl/src/main/java/org/apache/myfaces/context/servlet/StartupServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/webapp/ManagedBeanDestroyerListener.java

Allow an `HttpSession` to be set on `StartupServletExternalContextImpl` so that `javax.faces.bean.ViewScoped` cleanup can work correctly in `DefaultViewScopeProvider`
For https://issues.apache.org/jira/browse/MYFACES-4353

 MYFACES-4353 javax.faces.bean.ViewScoped cleanup 2.2.x

---

impl/src/main/java/org/apache/myfaces/context/servlet/StartupServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/webapp/ManagedBeanDestroyerListener.java

Allow an `HttpSession` to be set on `StartupServletExternalContextImpl` so that `javax.faces.bean.ViewScoped` cleanup can work correctly in `DefaultViewScopeProvider`
For https://issues.apache.org/jira/browse/MYFACES-4353

MYFACES-4353 save HttpSession for ViewScope cleanup 3.0.x

---

api/src/main/java/jakarta/faces/application/ProjectStage.java
api/src/main/java/jakarta/faces/application/StateManager.java
api/src/main/java/jakarta/faces/component/NamingContainer.java
api/src/main/java/jakarta/faces/component/UIComponent.java
api/src/main/java/jakarta/faces/render/ResponseStateManager.java

Similar to PR #124
4.0 already has a number of deprecated functions removed, so that's why the number of annotations
is much smaller. 
Few Notes:
- api/src/main/resources/META-INF/componentClass20.vm already had setValueBinding removed
- StateManager#restoreView was missing deprecated comment
- UIViewRoot#METADATA_FACET_NAME was already properly set
https://issues.apache.org/jira/browse/MYFACES-4372

MYFACES-4372 -- Fix JNDI Name & Add Deprecated Annotations (4.0 Branch)

---

impl/src/test/resources/org/apache/myfaces/config/jsf22-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf23-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf30-faces-config.xml

Needed to pass license check:
`Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check`

Add missing licenses

---

impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_3_0.xsd

The supported Faces Config versions need an update because the current `web-facesconfig_3_0.xsd `doesn't specifically support version 3.0.
See https://issues.apache.org/jira/browse/MYFACES-4374
This fix is one option.  Otherwise, see #143

Support Range of Versions During Validations

---

.travis.yml
README.md

Trying to exclude jdks in the PRs, so only openjdk8 runs
Otherwise, cron jobs should run daily and build with every jdk listed.

[Draft] Testing Travis Builds in 3.0.x

---

.travis.yml

3.0.x Travis Builds are queued and not executing. I'm not sure why, but I'm looking into it. 
For now, I'm testing the exclusions on master branch.

Exclude jdks & linux-ppc64le from Travis CI  PR Builds (master branch)

---

parent/pom.xml
pom.xml

As part of the last release to get the old site generation to function I had to make the following updates: https://github.com/apache/myfaces/pull/112
Now for this release I'm getting the following error:
> [INFO] [INFO] BUILD FAILURE
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Total time: 03:41 min
> [INFO] [INFO] Finished at: 2021-02-03T10:55:42-05:00
> [INFO] [INFO] Final Memory: 106M/453M
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2.1:attached (make_assembly_src) on project myfaces-core-assembly: Failed to create assembly: Error creating assembly archive coresrc: posix is not a legal value …

Update maven-assembly-plugin to version 2.5.4

---

impl/src/main/java/org/apache/myfaces/el/resolver/LambdaBeanELResolver.java

PropertyNotFoundException was thrown if the name of the poperty requested was null, but it should really be thrown when the property itself is not found.  This patch changes the nullness check accordingly.
Before:
java.lang.NullPointerException: Cannot invoke "org.apache.myfaces.core.api.shared.lang.PropertyDescriptorWrapper.getWrapped()" because "pd" is null
at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:78)
at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:136)
After:
javax.el.PropertyNotFoundException: Property [x] not found on type [com.example.FooBar_ClientProxy]
at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getPropertyDescriptor(LambdaBeanELResolver.java:162)
at …

MYFACES-4380 LambdaBeanELResolver: Fix PropertyNotFoundException condition

---

impl/src/main/java/org/apache/myfaces/cdi/impl/CDIManagedBeanHandlerImpl.java

This avoids "@SessionScoped does not exist within current thread" when
trying to destroy ViewScoped and FlowScoped beans.
Signed-off-by: Juri Berlanda <juri.berlanda@tuwien.ac.at>

MYFACES-4382: Add check if SessionScope is active.

---

api/src/main/java/jakarta/faces/component/html/_HtmlInputFile.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlInputFileRendererBase.java

I feel like an alien in this code base!
I didn't see any existing tests to update so i wasn't even sure where to begin to add a test for this?

MYFACES-4390: HtmlInputFile multiple support

---

assembly/pom.xml

The release rollback didn't look to update the assembly pom.xml that was updated during the release.

Rollback 2.3-next-M6 assembly pom.xml

---

api/src/main/resources/jakarta/faces/Messages_pt.properties
api/src/main/resources/jakarta/faces/Messages_pt_BR.properties

Fix translation of jakarta.faces.validator.DoubleRangeValidator.NOT_IN_RANGE on api/src/main/resources/jakarta/faces/Messages_pt.properties and api/src/main/resources/jakarta/faces/Messages_pt_BR.properties

Fix translation of DoubleRangeValidator

---

api/src/main/resources/jakarta/faces/Messages_pt.properties

Fix translation on jakarta.faces.validator.DoubleRangeValidator.NOT_IN_RANGE

Fix wrong translation of DoubleRangeValidator

---

api/src/main/resources/javax/faces/Messages_pt.properties

Fix translation of javax.faces.validator.DoubleRangeValidator.NOT_IN_RANGE on Messages_pt.properties

Fix translation on Messages_pt.properties

---

api/src/main/java/jakarta/faces/component/html/_HtmlSelectManyCheckbox.java
api/src/main/java/jakarta/faces/component/html/_HtmlSelectOneRadio.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlCheckboxRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase.java

MYFACES-4412: Add new layout="list" attribute value to h:selectManyCheckbox and h:selectOneRadio so it renders `<ul>` instead of `<table>`
Also the `"border"` attribute was being completely ignored and always set to "0".  Followed Mojarra's example for this fix.
See: https://github.com/eclipse-ee4j/faces-api/issues/1574

MYFACES-4412: Add new layout="list"

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlSecretRendererTest.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlSecretRendererBase.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlTextRendererBase.java

MYFACES-4428 - Separate "begin tag" code from "end tag" code
JSF provides a encodeBegin() and an encodeEnd() method on a Renderer. MyFaces currently performs "begin tag" and "end tag" encoding in the encodeEnd(), which breaks any vendor-netural path for extensibility. This patch moves the "begin tag" encoding logic to the encodeBegin() function so the renderkit can be extended without needed to extend myfaces classes explicitly, but instead be called through the standard JSF api to start a tag.

MYFACES-4428 - Separate "begin tag" code from "end tag" code

---

extensions/quarkus/showcase/pom.xml
integration-tests/pom.xml
parent/pom.xml
pom.xml

I noticed this when switching branches that Faces 4.0 is still set for JDK 8 but its using JDK 11 features.

Faces 4.0 use JDK 11

---

.github/workflows/codeql-analysis.yml
.github/workflows/myfaces-ci.yml

Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

Set permissions for GitHub Actions

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextareaRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlTextareaRendererBase.java

… MyFaces currently performs "begin tag" and "end tag" encoding in the encodeEnd(), which breaks any vendor-neutral path for extensibility. This patch moves the "begin tag" encoding logic to the encodeBegin() function so the renderkit can be extended without needing to extend myfaces classes explicitly, but instead be called through the standard JSF api to start a tag.

MYFACES-4434 - HtmlTextareaRendererBase separate encode end and begin

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Because `ViewScopeBeanHolder ` has a `    private static final Random RANDOM_GENERATOR = new Random();` for creating GraalVm native images this class must be registered as a special native runtime initialization class.
```shell
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: 
com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: 
Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option …
```

2.3-next: ViewScopeBeanHolder register for Quarkus native image

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java
impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

Fix for MYFACES-4442: https://issues.apache.org/jira/browse/MYFACES-4442
**Current behavior:**
1) MyFacesContainerInitializer.onStartup
a) Checks clazzes from @HandlesTypes
b) Checks if a faces-config.xml is present.
c) If a or b
- Check if there are current FacesServlet mappings
- If there is a  FacesServlet defined set: FACES_SERVLET_FOUND(true)
- If there is not a FacesServlet defined, then dynamically add and set: FACES_SERVLET_ADDED_ATTRIBUTE(true)
2) StartupServletContextListener.contextInitialized
a) Call FacesInitializer.initFaces(ServletContext)
3) FacesInitializerImpl.initFaces
a) If !INITIALIZE_ALWAYS_STANDALONE
b) Use FacesServletMappingUtils to getFacesServletRegistration
c) if getFacesServletRegistration is null / 0 then perform other checks
d) Check …

MYFACES-4442: avoid UnsupportedOperationException

---

api/src/main/java/javax/faces/context/ExternalContextWrapper.java

https://issues.apache.org/jira/browse/MYFACES-4454
https://github.com/apache/myfaces/blob/2.3-next/api/src/main/java/javax/faces/context/ExternalContextWrapper.java#L147
The other change for this in 4.0 doesn't look to exist in 2.3-next: https://github.com/apache/myfaces/blob/2.3-next/api/src/main/java/javax/faces/render/Renderer.java#L144 (still uses UIComponent correctly vs T)
This is just reverting the same change that was made to the API in 4.0 to cause signature test failures.

MYFACES-4454

---

api/src/main/java/jakarta/faces/component/html/_HtmlInputText.java
api/src/main/java/jakarta/faces/component/html/_TypeProperty.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlTextRendererBase.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextRendererTest.java

Adds type to HtmlInputText and adds unit tests proving the default is still `type="text"` but can now be set properly on the tag like `type="tel"` etc.

MYFACES-4456: Add type to HtmlInputText

---

impl/src/main/java/org/apache/myfaces/push/EndpointImpl.java
impl/src/main/java/org/apache/myfaces/push/WebsocketComponentRenderer.java
impl/src/main/java/org/apache/myfaces/push/cdi/PushContextImpl.java
impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketScopeManager.java
impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketSessionManager.java

- reworked channel token generation - new token is generated only if needed (ie new session/view), just one token for application scope
- fixed usage of user-specified channel - now also works even in application scope calls
- changed default max idle timeout for websockets - according to omnifaces/mojarra spec
- specified default websocket scope - according to documentation (session scope for user-specified websocket as default)

MYFACES-4445: websockets refactoring

---

impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java
impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

https://issues.apache.org/jira/browse/MYFACES-4447
The only difference between this PR and the changes for Faces 4.0: https://github.com/apache/myfaces/pull/329/files is I modified the comment in MyFacesContainerInitializer.java to reflect a `MyFaces` feature vs `Faces` feature as it wasn't spec'd until Faces 4.0 as well as updated the reference to `AbstractFacesInitializer` rather than `FacesInitializerImpl ` since these classes are different across the various branches. Of course imports are `javax` and not `jakarta`

MYFACES-4447: avoid UnsupportedOperationException

---

api/src/main/java/jakarta/faces/component/html/_HtmlDoctype.java

https://issues.apache.org/jira/browse/MYFACES-4455
Previous to this fix:
`public class HtmlDoctype extends jakarta.faces.component.UIOutput`
After this fix:
```
public class HtmlDoctype extends jakarta.faces.component.UIOutput
implements jakarta.faces.component.Doctype
```

MYFACES-4455: Add implementz to _HtmlDoctype JSFComponent

---

impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketScopeManager.java

- only websockets created attached to session scope are removed (not application scope)

MYFACES-4445: websockets refactoring - close sessionScope fix

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImplEventManager.java

https://issues.apache.org/jira/browse/MYFACES-4495

MYFACES-4495: Throw NPE when necessary

---

api/src/main/java/jakarta/faces/component/FacesComponent.java
impl/src/main/java/org/apache/myfaces/config/annotation/AnnotationConfigurator.java
impl/src/main/java/org/apache/myfaces/config/element/FacesConfig.java
impl/src/main/java/org/apache/myfaces/config/impl/FacesConfigDispenserImpl.java
impl/src/main/java/org/apache/myfaces/config/impl/element/FacesConfigImpl.java

I've also changed componentTagDeclarations / unmodifiableComponentTagDeclarations from a  Map to a List to avoid key conflicts and I noticed keys weren't even used (only the values).  Unless a Map was intentional to avoid duplicates, but a set should have been used instead? Nevertheless, Map changed to List and all our unit tests still pass. 
https://issues.apache.org/jira/browse/MYFACES-4493

MYFACES-4493: Allow Jakarta and JCP namespaces for FacesComponent

---

impl/src/main/java/org/apache/myfaces/context/servlet/PartialViewContextImpl.java

Since it's now done in the startDocument call.
This caused the preamble to be written twice which in turn caused some pages to fail since the JS wasn't expecting two preambles.

MYFACES-4501 follow up: Remove writePreamble

---

api/src/main/java/jakarta/faces/component/UIComponent.java

Fixing localized composite behaviour (3.0.x)

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Dom.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js

https://issues.apache.org/jira/browse/MYFACES-4498: fix for the head element replace code.
Code now works as expected, is smaller. Downside, cutoff now is IE9 for the head and bode replacement operations.
The simplified code was backported to older browsers from our new codebase

https://issues.apache.org/jira/browse/MYFACES-4498:

---

api/src/main/javascript/META-INF/resources/myfaces/api/faces.js
impl/src/main/java/org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.java

Fix for MYFACES-4040, in my own integration tests:
```xml
<h:commandLink id="submitButton" value="Click here" action="#{myBean2.execute}">
<f:ajax execute="@this" render="output" />
<f:param name="hello2" value="Hello from f:param"/>
<f:param name="Hello World" value="Hello from f:param2"/>
<f:param name="render" value="output2"/>
<f:param name="execute" value="booga"/>
</h:commandLink>
<h:panelGroup id="results">
<h:outputText id="output" value="#{myBean2.helloWorld}"></h:outputText>
</h:panelGroup>
```
Now resolves to:
```html
<a href="#" onclick="faces.util.chain(this, event,function(event){myfaces.ab(this,event,'action','submitButton','output',{params: {'hello2':'Hello from f:param','Hello World':'Hello from f:param2','render':'output2','execute':'booga'}})}); return false;" …
```

Fix for https://issues.apache.org/jira/browse/MYFACES-4040

---

impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlCheckboxRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase.java

Based on the SPEC issue here: https://github.com/jakartaee/faces/issues/1574
When layout="list" the border attribute should be ignored. 
When a form like this:
```xml
<h:form id="form">
<h:selectManyCheckbox id="input" layout="list" border="5">
...
</h:selectManyCheckbox>
</h:form>
```
Is rendered the current output is: 
```xml
<html>
<head/>
<body>
<form id="form" name="form" method="post" action="/LayoutAttribute/selectManyCheckBox.xhtml" enctype="application/x-www-form-urlencoded">
<ul id="form:input" border="5">
...
</ul>
</body>
</html>
```
Based on the spec we should be rendering: 
```xml
<html>
<head/>
<body>
<form id="form" name="form" method="post" action="/LayoutAttribute/selectManyCheckBox.xhtml" enctype="application/x-www-form-urlencoded">
<ul id="form:input">
...
</ul> …
```

[SPEC 1574 / MYFACES-4528 ] Ensure top level ul does not have border attribute

---

integration-tests/ajax/src/test/java/org/apache/myfaces/core/integrationtests/ajax/IntegrationTest.java
integration-tests/ajax/src/test/resources/arquillian.xml
integration-tests/autoLookupExpressionFactoryWithoutJSP/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/autoLookupExpressionFactoryWithoutJSP/src/test/resources/arquillian.xml
integration-tests/automaticExtensionlessMapping/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/automaticExtensionlessMapping/src/test/resources/arquillian.xml
integration-tests/exactMapping/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/exactMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMapping/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/faceletToXhtmlMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMappingDisabled/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/faceletToXhtmlMappingDisabled/src/test/resources/arquillian.xml
integration-tests/pom.xml
integration-tests/protectedViews/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/protectedViews/src/test/resources/arquillian.xml
pom.xml

There are two problems with the integration tests.
- The Maven embedded build in the integration tests can't resolve the produced artifacts of myfaces because that is a new Maven build. Moving the execution of the integration tests after the package phase allows to reference the produced war with the myfaces artifacts.
- chrome should be headless

fix: enable integration tests

---

integration-tests/pom.xml

During the RC3 release prep, maven asked me: 
```
...
What is the release version for "Apache MyFaces Core 4.0 - Integration Tests - ajax"? (org.apache.myfaces.core.integration-tests:ajax) 4.0.0: : 4.0.0-RC3
What is the release version for "Apache MyFaces Core 4.0 - Integration Tests - automaticExtensionlessMapping"? (org.apache.myfaces.core.integration-tests:automaticExtensionlessMapping) 4.0.0: : 4.0.0-RC3
...
```
Rather not deploy this integration tests module as it's just testing, so I added the skip configuration.

Skip integration-tests deployment

---

integration-tests/ajax/src/main/java/org/apache/myfaces/core/integrationtests/ajax/test1Protocol/responseWriter/PartialResponseWriterImpl.java

```
[INFO] [ERROR]                                                   ^
[INFO] [ERROR] /Users/volosied/opensource/myfaces/target/checkout/integration-tests/ajax/src/main/java/org/apache/myfaces/core/integrationtests/ajax/test1Protocol/responseWriter/PartialResponseWriterImpl.java:37: error: bad use of '>'
[INFO] [ERROR]  * Flow UIViewRoot: insert or update -> eval  javascripts must be deferred
[INFO] [ERROR]                                       ^
[INFO] [ERROR] /Users/volosied/opensource/myfaces/target/checkout/integration-tests/ajax/src/main/java/org/apache/myfaces/core/integrationtests/ajax/test1Protocol/responseWriter/PartialResponseWriterImpl.java:40: error: bad use of '>'
[INFO] [ERROR]  * insert or update -> script src type="text/javascript"
...
```
Now shows:
integration-tests % …

Fix javadoc "bad use of '>'" errors

---

api/src/assembler/jsdoc-compiler.xml
api/src/assembler/jsfscripts-compiler.xml
api/src/assembler/jsfscripts-experimental.xml
api/src/assembler/jsfscripts-legacy.xml
api/src/assembler/jsfscripts-minimal-compiler.xml
api/src/assembler/jsfscripts-minimal-modern-compiler.xml
api/src/assembler/jsfscripts-uncompressed-compiler.xml
api/src/assembler/jsfscripts-uncompressed-full-compiler.xml
api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Dom.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/_EvalHandlers.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/_ExtRuntime.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/_Runtime.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/ObjectQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_AjaxRequestQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_AjaxResponseQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_DomQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_LangQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_RuntimeQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_TransportQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/readme.txt
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxRequest.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_Transports.js
api/src/main/javascript/META-INF/resources/myfaces/api/jsf.js

Also related to: https://issues.apache.org/jira/browse/MYFACES-4535
This pr unifies the code between 2.3-next and 3.0 and 4.0
Also backwards compatibility to older browsers has been improved by readding the shim layer from 2.3, now that it has a clear boundary.
Unused Ext code has been removed.
Synching between next and 3.0 now should be relatively straight forward.
Also all patches which have been added to 2.3 also are now active in this one
The only fix missing is the f:param TCK fix, which needs also patches on the impl side.

https://issues.apache.org/jira/browse/MYFACES-4538: 3.0.x

---

impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java

Current code has the early flow transition after a FlowCallNode, but it should be before.  This was mistaken done in the previous PR: https://github.com/apache/myfaces/pull/504
Otherwise, the some flows might not transition due to the `for (int i = didFlowTransitionAlready(facesContext) ? 1 : 0` in applyFlowTransition. 
Basically, a flow could transition into the same one twice.  
Rough outline...
1) Not in flow
2) getNavigationCase, begin the node algorithm, and Hit Flow Node
3) Restart node algorithm
4) early transition into flow for nested flow
5) The navigationContext.targetFlows has two flows.  Since the transition marker was set, the first flow would be skipped.     It would transition into the second flow and miss the first.

MYFACES-4553 - fix placement of flow transition

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js

With the MYFACES-4533 fix (#510) merged in, we tries to run our test suite against it and found this htmlunit/javascipt error hitting numerous tests:
`Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function getAttribute in object [object Text]. (http://localhost:8010/JSF22Miscellaneous/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development#5213) `
Manual tests via web browser show no errors so this problem looks to be just another HTMLUnit bug. 
As a workaround for now, I'd like to test if this is a function so that these tests can pass.

JavaScript: Check if getAttribute is a function before calling it (MYFACES-4533 follow up)

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java
impl/src/main/resources/META-INF/WebConfigParamsLogger.vm

https://issues.apache.org/jira/browse/MYFACES-4561
Although the hope was to not log these context param messages in production. That change would have unintended consequences since the params then won't be logged in at all.  This can make it difficult to debug applications if there's no trace regarding the context parameters. 
I add new logging and refactored the code, so the new behavior is now: 
auto - logs in dev mode only
true - logs in production and dev mode
false - no logging in either mode (fine messages still logged when trace is specified -- added for support)
Other project stage modes are not considered. 
Additionally,  _found_ context parameters are now logged.

MYFACES-4561 Change Context Parameter Logging

---

integration-tests/ajax/src/test/java/org/apache/myfaces/core/integrationtests/ajax/IntegrationTest.java

Fixing the reported issue by @volosied!
It was a race condition caused by a wait window of 0 which means immediate result expected otherwise error!

Fix for: https://issues.apache.org/jira/browse/MYFACES-4564

---

api/src/client/typescript/faces/impl/AjaxImpl.ts

https://issues.apache.org/jira/browse/MYFACES-4572
Previous JS code: 
```
getProjectStage:function () {
....
}
else {
//we found the script, but there was no stage parameter -- Production
//(we also add an override here for testing purposes, the default, however is Production)
projectStage = getConfig(PRJ_STAGE, STG_PROD);
}
}
}
/* we could not find anything valid --> return the default value */
this._projectStage = getConfig(PRJ_STAGE, projectStage || STG_PROD);
}
```

MYFACES-4572 - Return 'Production' as default project stage

---

extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/QuarkusFacesInitializer.java
impl/src/main/java/org/apache/myfaces/cdi/model/FacesDataModelManager.java

@tandraschko this works but still generates this warning:
```
Called FactoryFinderProviderFactory.setFactory after initialized FactoryFinder (first call to getFactory() or setFactory()). This method should be called before any 'web context' is initialized in the current 'classloader context'. By that reason it will not be changed.
```
But everything seems to be working and hot reload works again.
I had to remove the unmodifiable map or else it also throws an exception trying to add the models.

MYFACES-4582: Quarkus hot reload

---

api/pom.xml
assembly/pom.xml
bundle/pom.xml
extensions/pom.xml
extensions/quarkus/deployment/pom.xml
extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
impl/pom.xml
parent/pom.xml
pom.xml
test/pom.xml

`mvn release:rollback` didn't work since I don't have the backup poms, so I'm doing a manual revert here. 
This reverts commit ff9f09afdbc6c83a70d885433fcc15c1749ab1ac.
This reverts commit c70c4bf9b15160f06fefdc0fb3cb76e42a4ad73c.

Revert 2.3-next-M8 release

---

extensions/quarkus/pom.xml

Quarkus 3.0 went final so I figured this is what we should compile against.

Quarkus 3.0.0 Final

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4604

MYFACES-4604: Update f:websocket integration message

---

bundle/pom.xml

Accidentally forgot about this.  Thoughts on the versions? 
Should I use 
[1.8.0, 2.1.0]
or 
[1.8.0, 3.0.0) 
2.1 is the latest currently.

Update import package version for digester

---

impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImpl.java
impl/src/main/java/org/apache/myfaces/context/servlet/FacesMessageIterator.java

Because its a LinkedHashMap and the Lists they will remain ordered but not in separate storage containers.

MYFACES-4612: FacesMessages don't store in different collections

---

api/src/main/java/jakarta/faces/context/ExternalContext.java
api/src/main/java/jakarta/faces/context/ExternalContextWrapper.java

for `https://github.com/jakartaee/faces/issues/1764`

Spec 1764 : Add ExternalContext#setResponseContentLengthLong to API

---

impl/src/main/java/org/apache/myfaces/cdi/FacesArtifactProducer.java

I think this is the right way to do it?
The spec issue also requested conversation scopes to be injectable, but that's done via CDI. 
See https://docs.jboss.org/weld/reference/2.4.0.CR1/en-US/html/scopescontexts.html#_the_conversation_scope ( 5.3.1)

Spec 1342 : Make Flows Injectable

---

impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java

Missed in https://github.com/apache/myfaces/pull/617
Additionally, I don't see any mention of getters in the spec, so only the setter is implemented.

Create setResponseContentLengthLong in ServletExternalContextImpl

---

impl/src/main/java/org/apache/myfaces/view/facelets/PartialStateManagementStrategy.java
integration-tests/myfaces4623/pom.xml
integration-tests/myfaces4623/src/main/java/org/apache/myfaces/core/integrationtests/Bean.java
integration-tests/myfaces4623/src/main/java/org/apache/myfaces/core/integrationtests/CustomComponent.java
integration-tests/myfaces4623/src/main/webapp/WEB-INF/beans.xml
integration-tests/myfaces4623/src/main/webapp/WEB-INF/faces-config.xml
integration-tests/myfaces4623/src/main/webapp/WEB-INF/web.xml
integration-tests/myfaces4623/src/main/webapp/index.xhtml
integration-tests/myfaces4623/src/main/webapp/resources/default/js/test.js
integration-tests/myfaces4623/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/myfaces4623/src/test/resources/arquillian.xml
integration-tests/pom.xml

Draft test fix for https://issues.apache.org/jira/browse/MYFACES-4623
Feel like a band-aid solution on top of another band-aid :/ 
This could use some refactoring to avoid code duplication?

MYFACES-4623 check for duplicate ids

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/composite/ExtensionHandler.java

TLDDocs are updated via the class comment and a warning is logged once.

Deprecate composite:extension

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js

Fix for MyFaces 4606, checkboxes and radio buttons are not appended automatically if unchecked!

Follow up on https://issues.apache.org/jira/browse/MYFACES-4606

---

api/src/main/java/jakarta/faces/annotation/View.java
impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java

NonBinding isn't needed due to the regression mentioned below, but extension-less views for programmatic views now works.

Myfaces 4644 5.0

---

api/src/main/java/jakarta/faces/validator/ValidatorException.java
impl/src/test/java/jakarta/faces/validator/ValidatorExceptionTest.java

Fixes [MYFACES-4646](https://issues.apache.org/jira/browse/MYFACES-4646) by only adding the FacesMessage detail to the ValidatorException message if it is not empty

MYFACES-4646: Fix formatting of string built by ValidatorException

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java

The following warnings are logged when the context parameters are used:
```
[WARNING ] The configuration 'jakarta.faces.PARTIAL_STATE_SAVING' is deprecated as of Faces 4.1
[WARNING ] The configuration 'jakarta.faces.FULL_STATE_SAVING_VIEW_IDS' is deprecated as of Faces 4.1
```
Once approved, I'll update main (5.0) directly.

Fix typo and log warning indicating jakarta.faces.FULL_STATE_SAVING_VIEW_ID is deprecated

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

5.0: Quarkus RepeatStatus reflection, 3.8.4 LTS
This needs to be a reflected as its a POJO and if you reference it in EL for index it fails in Native mode

5.0: Quarkus RepeatStatus reflection

---

impl/src/main/java/org/apache/myfaces/view/facelets/component/UIRepeat.java

Discovered via TCK testing.
The saveState method wasn't property updated, but it's fixed now.  I used UIData as a reference. 
I added a test case previously, but the TCK is a bit more thorough ( nested ui reeats). 
https://issues.apache.org/jira/browse/MYFACES-4664

Fix up rowStatePreserved in UIRepeat

---

api/src/client/typescript/faces/impl/PushImpl.ts

Fixes [MYFACES-4671](https://issues.apache.org/jira/browse/MYFACES-4671)
Which is related to the following [OpenLiberty issue](https://github.com/OpenLiberty/open-liberty/issues/27598)
event.data can sometimes be undefined, so this prevents it from being undefined by changing event.data to null in the case when event.data is undefined.

Fixes MYFACES-4671

---

api/src/main/java/jakarta/faces/component/UIViewRoot.java
impl/src/test/java/org/apache/myfaces/view/facelets/tag/faces/core/reset/ResetValuesTestCase.java
impl/src/test/resources/org/apache/myfaces/view/facelets/tag/faces/core/reset/resetValuesActionListener_4.xhtml
impl/src/test/resources/org/apache/myfaces/view/facelets/tag/faces/core/reset/resetValuesActionListener_5.xhtml

@tandraschko this is your ported fix from 5.0 but I don't see you doing anything with `PartialViewContextImpl.java` ???
That still just has this:
```java
// same like UIViewRoot#ResetValuesCallback
private static class ResetValuesCallback implements VisitCallback
{
public VisitResult visit(VisitContext context, UIComponent target)
{
if (target instanceof EditableValueHolder)
{
((EditableValueHolder)target).resetValue();
}
return VisitResult.ACCEPT;
}
}
```

MYFACES-4675: 4.0 ResetValues visit tree

---

api/src/main/java/org/apache/myfaces/core/api/shared/lang/ClassUtils.java
impl/src/main/java/org/apache/myfaces/application/FacesServletMappingUtils.java
impl/src/main/java/org/apache/myfaces/util/lang/ClassUtils.java

https://issues.apache.org/jira/browse/MYFACES-4666
By throwing the faces exception, this logic causes apps to fail during start-up. In our scenario, it happens to the servlet TCK app, as reported in this challenge : `https://github.com/jakartaee/servlet/issues/691` 
This PR tries to find a balance between allowing the app to start up while also alerting the user of the non-existent servlet class. 
The git diff is a bit wonky -- the new simpleClassForName method is the second one, not the first as git shows.

MYFACES-4666: Overload simpleClassForName -- new param to log exception only

---

api/src/client/typescript/faces/impl/core/Const.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/xhrCore/EventTests.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest_23.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts

Reverts change for https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4676
Taken from comment in JIRA above:
```
I think this is causing 3 new errors in the TCK:   (linked the 4.1.0 TCK but I tested 4.0 code)
_____
Name: undefined Error:  decode: A RuntimeException Has Occurred!
http://localhost:9080/test-faces22-ajax/issue2179-page2.xhtml
https://github.com/jakartaee/faces/blob/4.1.0-RELEASE/tck/faces22/ajax/src/test/java/ee/jakarta/tck/faces/test/servlet30/ajax_selenium/Issue2179IT.java#L49
____
Error from undefined 
http://localhost:9080/test-faces22-ajax/ajaxScriptError.xhtml
https://github.com/jakartaee/faces/blob/4.1.0-RELEASE/tck/faces22/ajax/src/test/java/ee/jakarta/tck/faces/test/servlet30/ajax_selenium/Issue3473IT.java#L35
____
Error from undefined …
```

Revert MYFACES-4676 due to TCK failures

---

api/pom.xml
api/src/main/java/jakarta/faces/component/ActionSource.java
api/src/main/java/jakarta/faces/component/ActionSource2.java
impl/pom.xml
parent/pom.xml

https://issues.apache.org/jira/browse/MYFACES-4692
Code looks right, but I'm getting a build error: 
`
[ERROR] Failed to execute goal org.apache.myfaces.buildtools:myfaces-builder-plugin:1.0.11:build-metadata (default) on project myfaces-api: Execution default of goal org.apache.myfaces.buildtools:myfaces-builder-plugin:1.0.11:build-metadata failed: syntax error @[48,1] in file: myfaces/api/src/main/java/jakarta/faces/component/ActionSource.java -> [Help 1]
`

MYFACES-4692: provide default implementations for getActionExpression and setActionExpression

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
impl/pom.xml
impl/src/main/conf/META-INF/standard-faces-config-base.xml
impl/src/main/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtils.java
impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java
impl/src/main/java/org/apache/myfaces/view/facelets/compiler/TagLibraryConfigUnmarshallerImpl.java
impl/src/main/resources/META-INF/faces-config20.vm
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_11.xsd
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_web_services_client_2_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_8.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_web_services_client_1_4.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_2_2.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_2_3.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_3_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_4_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_4_1.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_4_1.xsd

Pulled from https://jakarta.ee/xml/ns/jakartaee/
1)  web services client xsd was pulled in to fix this error: 
```
jakarta.faces.FacesException: org.xml.sax.SAXParseException; systemId: file:... jakartaee_11.xsd; lineNumber: 106; columnNumber: 52; src-resolve: Cannot resolve the name ‘jakartaee:service-refGroup’ to a(n) ‘group’ component.
```
2) standard config xml was updated to 2.3 because `<client-window-factory>org.apache.myfaces.lifecycle.clientwindow.ClientWindowFactoryImpl</client-window-factory>` is used. It was added in 2.3. OTherwise validation failures for 2.0 to 2.2. 
3) Added support for XML validation for 2.2-4.1
4) DTD for 1.0 still works. Verifed via 
```
<?xml version="1.0"?>
<!DOCTYPE facelet-taglib PUBLIC
"-//Sun Microsystems, Inc.//DTD Facelet Taglib 1.0//EN" …
```

MYFACES-4654: Support Schema Validation for 4.1

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
impl/pom.xml
impl/src/main/conf/META-INF/standard-faces-config-base.xml
impl/src/main/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtils.java
impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java
impl/src/main/java/org/apache/myfaces/view/facelets/compiler/TagLibraryConfigUnmarshallerImpl.java
impl/src/main/resources/META-INF/faces-config20.vm
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_11.xsd
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_web_services_client_2_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_8.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_web_services_client_1_4.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_2_2.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_2_3.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_3_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_4_0.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facelettaglibrary_4_1.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_4_1.xsd

This still needs work, but it syncs the code up somewhat with 4.1. 
Future work for this branch will be done via  MYFACES-4697.

Myfaces 4654 [5.0]

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/core/Const.ts
api/src/client/typescript/faces/impl/util/ExtDomQuery.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/util/ExtDomQueryTest.spec.ts
api/src/client/typescript/faces/test/myfaces/OamSubmit.spec.ts
api/src/client/typescript/faces/test/xhrCore/ErrorChainTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/XhrRequestProgress.spec.ts

Fixes
https://issues.apache.org/jira/browse/MYFACES-4676,
https://issues.apache.org/jira/browse/MYFACES-4691
And adds
https://github.com/werpu/jsfs_js_ts/issues/52:
A non intrusive extension which adds upload percentage tracking capabilities, per request of Tobago!

Various JS codebase fixes (see description)

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/@types/definitions/index.d.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/EventData.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest_23.spec.ts

https://issues.apache.org/jira/browse/MYFACES-4699:

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java
impl/src/main/java/org/apache/myfaces/cdi/JsfArtifactProducer.java
impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
impl/src/test/java/org/apache/myfaces/component/search/SearchExpressionImplTest.java
shared/src/main/java/org/apache/myfaces/shared/application/FacesServletMappingUtils.java

3 Changes Identified 
1) [MYFACES-4524](https://issues.apache.org/jira/browse/MYFACES-4524) breaks the TCK since it's testing the incorrect behavior, but I don't know how to update the TCK. I created a challenge here - `https://github.com/jakartaee/faces/issues/1976` 
2) `node.getAttribute` gives me errors when I run the TCK, so I've added a check to try to avoid the error.
3) Assert over Assertions
4) Reverts breaking changes (listed under MYFACES-4705)

Prep for a 2.3.11 release 

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java

If the _""_ default value is used, it produces the following code in 
`            logMessageToAppropriateLevel("No context init parameter 'org.apache.myfaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING' found, using default value '""'.");` 
This leads to a compilation error via ` value '""'."`.  I'll just exclude the default value to get this working again.

Remove default value from EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java

As part of https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4705, I think we can add this change back in.
It not really a breaking change, since a NPE would be thrown anyway (just in the method).

[2.3.x] Add MYFACES-4495: Throw NPE when necessary back in 

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java

As part of https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4705, I think we can add this change back in.
It not really a breaking change, since a NPE would be thrown anyway (just in the method).

Re-Introduce MYFACES-4495 

---

impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

As described in the comment: 
```
* ... the listener checks if 
* the FacesServlet has already been defined in web.xml and if not, it adds
* the FacesServlet with the mappings (/faces/*, *.jsf, *.faces) dynamically.
```
In summary, if this annotation is found and the web.xml doesn't have any mappings listed for the faces servlet, they will be added automatically. 
I'm assuming this was mise when this annotation was added 2.3

MYFACES-4709: Add FacesConfig to HandlesTypes

---

extensions/quarkus/runtime/pom.xml

4.0 uses Java 11, but Tomcat Jasper EL 11 is compiled with Java 17. So we need to downgrade 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project myfaces-quarkus-deployment: Compilation failure
[ERROR] ~/myfaces/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java:[73,21] cannot access org.apache.el.ExpressionFactoryImpl
[ERROR]   bad class file ~/.m2/repository/org/apache/tomcat/tomcat-jasper-el/11.0.0/tomcat-jasper-el-11.0.0.jar(/org/apache/el/ExpressionFactoryImpl.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

Lower tomcat-jasper-el dependency to 10.1.34 to avoid class file version mismatch

---

impl/src/main/java/org/apache/myfaces/context/ExceptionHandlerUtils.java

1) I split the loop up into two parts for readability/simplicity.  One for the FacesWrapper and the other for the FacesException/ELException.
2) Added a check for null. If so,  we exit the loop.

[4.1.x] Avoid NPE in logException's while loop

---

api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/test/xhrCore/EventTests.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts

The following test failed: 
ee.jakarta.tck.faces.test.servlet30.ajax_selenium.Issue2179IT#testDecodeException 
https://github.com/jakartaee/faces/blob/4.1.2-RELEASE/tck/faces22/ajax/src/test/java/ee/jakarta/tck/faces/test/servlet30/ajax_selenium/Issue2179IT.java#L49 
**Expected:** 
Name: form:submit Error: serverError
**Actual:** 
Name: form:submit Error:  decode: A RuntimeException Has Occurred!
The `serverError` string was missing, so I added it back in.

[4.0.x] Add serverError prefix to comply with TCK

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

Since we released 4.1.0 already, I want to keep the property name the same.
In 5.0, we can update `o.a.m.AUTOCOMPLETE_OFF_VIEW_STATE` to `o.a.m.AUTOCOMPLETE_VIEW_STATE_VALUE` or something similar.

[4.1] MYFACES-4721: Update AUTOCOMPLETE_OFF_VIEW_STATE ('one-time-code' as default)

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js

It previously was supported, but got lost in the refactoring. I'm adding it back in.
Added to 2.3.x here: e5966675d8cf869e60da8c948b9fc96d108e5868

Add delay of 'none' value to 3.0.x

---

impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketScopeManager.java
impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketSessionManager.java

1/ when the view is destroyed (i.e. the user reaches the NUMBER_OF_VIEWS_IN_SESSION limit), sessionScope channels are not destroyed. Channel could still be active for other views or newly created ones. In other words, session-scoped channels only get destroyed when the entire session is destroyed.
2/ we have to track number of user channelToken usage connections (when the user is using same channelToken in multiple browser windows / tabs with same http session, the channelToken remains same), and we can't close this channel until all user connections to this channel are closed (all tabs/windows).

MYFACES-4660 4.0 view destroying fix + keeping track of user connection in multiple tabs
