api/src/main/java/javax/faces/view/facelets/FaceletContext.java

https://issues.apache.org/jira/browse/MYFACES-4234

MYFACES-4234 Use intern() on FACELET_CACHE_KEY value

---

impl/src/main/java/org/apache/myfaces/ee/MyFacesContainerInitializer.java
impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java

Fix the web-fragment issue described in MYFACES-3629

MYFACES-3629 add context attr for case when faces servlet is found by SCI

---

impl/src/main/java/org/apache/myfaces/ee6/MyFacesContainerInitializer.java
impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java

Fixing this issue on the 2.2 branch

MYFACES-3629 add context attr for case when faces servlet is found by SCI - 2.2.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

fixes https://issues.apache.org/jira/browse/MYFACES-4252

MYFACES-4252 fix Classpath._searchDir NPE 2.0.X

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

fixes https://issues.apache.org/jira/browse/MYFACES-4252

MYFACES-4252 fix Classpath._searchDir NPE 2.1.X 

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

fixes https://issues.apache.org/jira/browse/MYFACES-4252

MYFACES-4252 fix Classpath._searchDir NPE 2.2.X

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

fixes https://issues.apache.org/jira/browse/MYFACES-4252

MYFACES-4252 fix Classpath._searchDir NPE

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

https://issues.apache.org/jira/browse/MYFACES-4267

MYFACES-4273 close() JarFile in Classpath 2.3.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

https://issues.apache.org/jira/browse/MYFACES-4273

MYFACES-4273 close() JarFile in Classpath 2.2.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

https://issues.apache.org/jira/browse/MYFACES-4267

MYFACES-4273 close() JarFile in Classpath 2.1.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

https://issues.apache.org/jira/browse/MYFACES-4267

MYFACES-4273 close() JarFile in Classpath 2.0.x

---

impl/src/test/resources/org/apache/myfaces/view/facelets/stateless/stateless.xhtml
impl/src/test/resources/org/apache/myfaces/view/facelets/stateless/template.xhtml

Without this I get a failure when trying to perform a new release: 
[INFO] [ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project myfaces-impl: Too many files with unapproved license: 2 See RAT report in:

Update Missing License on test files

---

impl/src/main/java/org/apache/myfaces/shared_impl/webapp/webxml/WebXml.java

https://issues.apache.org/jira/browse/MYFACES-4284

MYFACES-4284 fix CNFE in getFacesServletMappings

---

impl/src/main/java/org/apache/myfaces/shared_impl/webapp/webxml/WebXml.java

https://issues.apache.org/jira/browse/MYFACES-4284

MYFACES-4284 fix CNFE in getFacesServletMappings 2.2.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/compiler/SAXCompiler.java
impl/src/test/java/org/apache/myfaces/view/facelets/compiler/SkipNamespaceUnitTest.java
impl/src/test/resources/org/apache/myfaces/view/facelets/compiler/testSkipNamespaceUnit.xhtml

changes in o.a.m..view.facelets.compiler.SAXCompiler (skip html namespaces unit compilation)
add org.apache.myfaces.view.facelets.compiler;SkipNamespaceUnitTest.java
add test resource testSkipNamespaceUnit.xhtml

Myfaces-4281

---

impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/test/java/org/apache/myfaces/context/servlet/FacesContextImplBaseTest.java

For https://issues.apache.org/jira/browse/MYFACES-4282

MYFACES-4282 skip clearing view map during view metadata creation

---

impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/test/java/org/apache/myfaces/context/servlet/FacesContextImplBaseTest.java

For https://issues.apache.org/jira/browse/MYFACES-4282

MYFACES-4282 skip clearing view map during view metadata creation 2.2.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/util/Classpath.java

…tions
Addresses a StringOutOfBoundsException that may be thrown in some applications.
See more information at https://issues.apache.org/jira/browse/MYFACES-4292 and https://github.com/apache/myfaces/pull/55

Catch StringOutOfBounds Exception in Classpath util - 2.0.x

---

impl/src/main/java/org/apache/myfaces/util/IllegalXmlCharacterFilterWriter.java

fix: do not treat spaces as invalid characters

---

api/src/main/java/javax/faces/convert/NumberConverter.java
impl/src/test/java/javax/faces/convert/NumberConverterTest.java

Change-Id: I1586ff486a5aa8b395606c76462e473bd6d60e4e

MYFACES-4293: handle BigInteger in NumberConverter

---

parent/pom.xml

MYFACES-4300 upgrade commons-beanutils to 1.9.4

---

parent/pom.xml

MYFACES-4300 upgrade commons-beanutils to 1.9.4 - 2.0.x

---

parent/pom.xml

MYFACES-4300 upgrade commons-beanutils to 1.9.4 - 2.2.x

---

parent/pom.xml

MYFACES-4300 upgrade commons-beanutils to 1.9.4 - 2.3.x

---

parent/pom.xml

MYFACES-4300 upgrade commons-beanutils to 1.9.4 - 2.1.x

---

api/pom.xml
assembly/pom.xml
bundle/pom.xml
impl-test/pom.xml
impl/pom.xml
parent/pom.xml
pom.xml
shared-public/pom.xml
shared/pom.xml

Need to make the following changes to the 2.2.x branch: https://github.com/apache/myfaces/commit/b80a8ccae74d8bf3c0be0de9cdbf9f1b16ae2e60#diff-04dc5d029560773ac79faaf3da0fbb22

Change scm from svn to git

---

impl/src/test/java/org/apache/myfaces/cdi/bean/CDIGenericConverterValidatorTest.java
impl/src/test/java/org/apache/myfaces/cdi/bean/CustomConverter.java
impl/src/test/java/org/apache/myfaces/cdi/bean/CustomValidator.java
impl/src/test/resources/org/apache/myfaces/cdi/bean/CDIGenericConverterTest.xhtml
impl/src/test/resources/org/apache/myfaces/cdi/bean/CDIGenericValidatorTest.xhtml

Port of https://github.com/apache/myfaces/pull/77 for master

Myfaces 4311 unittest

---

impl/src/main/java/org/apache/myfaces/config/MyfacesConfig.java

Majority of parameters were already removed except for this one.

Myfaces-3822 remove RENDER_FORM_SUBMIT_SCRIPT_INLINE param

---

impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java
shared/src/main/java/org/apache/myfaces/shared/config/MyfacesConfig.java

Please let me know if I should change the logging in the AbstractFacesInitializer.java or remove it entirely.
I don't see references to any of the parameters anywhere in the code, and all the tests pass, too.

MYFACES-3822-remove-unsued-parameters-2.3

---

impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java

For https://issues.apache.org/jira/browse/MYFACES-4320

MYFACES-4320 Startup ConcurrentModificationException 2.3.x

---

impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java

For https://issues.apache.org/jira/browse/MYFACES-4320

MYFACES-4320 Startup ConcurrentModificationException 2.2.x

---

impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java

For https://issues.apache.org/jira/browse/MYFACES-4320

MYFACES-4320 Startup ConcurrentModificationException 3.0.x

---

impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java

For https://issues.apache.org/jira/browse/MYFACES-4320

MYFACES-4320 fix ConcurrentModificationException 2.0.x

---

.travis.yml
README.md

you might have to trigger your project to travis-ci in page https://travis-ci.org/apache/myfaces

add travic-ci; add travis badge to README.md

---

impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java

2.2.x: Update partialStateSavingDefault to check for facesVersion >=2

---

impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java

2.3.x: Update partialStateSavingDefault to check for facesVersion >=2

---

impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java

3.0.x: Update partialStateSavingDefault to check for facesVersion >=2

---

extensions/quarkus/pom.xml
extensions/quarkus/showcase/README.md
extensions/quarkus/showcase/pom.xml

I also added `maven.compiler.release` parameter to showcase app, see [details here](https://github.com/oracle/graal/issues/1060#issuecomment-476566265).

update Quarkus extension to v1.4.2

---

extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/showcase/pom.xml
extensions/quarkus/showcase/src/test/java/org/apache/myfaces/core/extensions/quarkus/showcase/QuarkusMyFacesShowcaseTest.java

Also set graalvm native image dependency as provided

Update extension to quarkus 1.5.2

---

parent/pom.xml

With the latest release of myfaces-builder-plugin v1.0.11, I am updating the pom.xml in preparation for the 3.0.x release.

Update myfaces-builder-plugin to version 1.0.11

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

To define additional url mappings for example, it should be possible to define the faces servlet via the web.xml.
If it exists in web.xml, it is used for here. If not, a default faces servlet config is created from the extension.

If web.xml defines a faces servlet, take it from there

---

extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/showcase/src/main/resources/application.properties

- ignores .iml files in rat plugin
- Remove unused jackson dependency

Quarkus extension cosmetics

---

impl/src/main/java/org/apache/myfaces/el/unified/ResolverBuilderForFaces.java
impl/src/main/java/org/apache/myfaces/el/unified/ResolverBuilderForJSP.java

Fix for https://issues.apache.org/jira/browse/MYFACES-4362

MYFACES-4362: Uncomment BeanManager ELResolver addition

---

shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils.java
shared/src/main/java/org/apache/myfaces/shared/webapp/webxml/WebXmlParser.java

Fix for https://issues.apache.org/jira/browse/MYFACES-4364

Myfaces 4364: Fix missing jakarta renames

---

impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_3_0.xsd

Let me know if there are any concerns with this PR. Otherwise, I can working some of the issues I found next.
-     We must probably also add the new namespaces to FacesConfigurator.java
The only namespaces I saw were for  http://xmlns.jcp.org/jsf, http://xmlns.jcp.org/jsp, and http://xmlns.jcp.org/jstl. I don't are updated in EE9, but will in EE10. See https://github.com/eclipse-ee4j/faces-api/issues/1526
-     add 3.0 in faces-config-versionType in web-facesconfig_3_0.xsd
Updated to 3.0 
-     we often has stuff like public final static String NAMESPACE = "http://xmlns.jcp.org/jsp/jstl/functions";
Same as first point 
______________
Other items I noticed... 
Questions:  Is _impl/src/main/conf/META-INF/standard-faces-config-base.xml_ update necessary? I believe since this is a new …

MYFACES-4360: Faces Config 3.0

---

impl/src/main/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtils.java
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_9.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_7.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_2_2.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_2_3.xsd
impl/src/test/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtilsTestCase.java
impl/src/test/resources/org/apache/myfaces/config/jsf22-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf23-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf30-faces-config.xml

Fixes MYFACES-4363
Tested locally with the 2.2, 2.3, and 3.0 faces-config version & corresponding namespaces. 
Update: Tests added

MYFACES-4363: Correct xsd files for proper validation + Update Version Handling 

---

impl/src/main/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtils.java
impl/src/main/resources/org/apache/myfaces/resource/jakartaee_9.xsd
impl/src/main/resources/org/apache/myfaces/resource/javaee_7.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_2_2.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_2_3.xsd
impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_4_0.xsd
impl/src/test/java/org/apache/myfaces/config/ConfigFilesXmlValidationUtilsTestCase.java
impl/src/test/resources/org/apache/myfaces/config/jsf22-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf23-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf30-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf40-faces-config.xml

Fixed MYFACES-4363 on Master
Also, added testJSF40Config and impl handling for  jakartaee_10.xsd

Apply MYFACES-4363 to Master (4.0) 

---

impl/src/main/java/org/apache/myfaces/application/StateCache.java
impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: prefer SecureRandom for token generation 2.3.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: prefer SecureRandom for token generation

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: prefer SecureRandom for token generation 2.1.x

---

impl/src/main/java/org/apache/myfaces/application/StateCache.java
impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: prefer SecureRandom for token generation 2.2.x

---

impl/src/main/java/org/apache/myfaces/application/StateCache.java
impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: prefer SecureRandom for token generation 3.0.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: make sure SecureRandom is used for invalid configs 3.0.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/StateCacheClientSide.java
impl/src/main/java/org/apache/myfaces/application/viewstate/StateCacheServerSide.java

MYFACES-4373: make sure SecureRandom is used for invalid configs

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ClientSideStateCacheImpl.java
impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: make sure SecureRandom is used for invalid configs 2.2.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: make sure SecureRandom is used for invalid configs 2.0.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: make sure SecureRandom is used for invalid configs 2.1.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ClientSideStateCacheImpl.java
impl/src/main/java/org/apache/myfaces/application/viewstate/ServerSideStateCacheImpl.java

MYFACES-4373: make sure SecureRandom is used for invalid configs 2.3.x

---

impl/src/main/java/org/apache/myfaces/application/viewstate/StateCacheServerSide.java
impl/src/main/java/org/apache/myfaces/config/MyfacesConfig.java

MYFACES-4373: prefer SecureRandom for token generation 2.3-next

---

.github/workflows/myfaces-ci.yml

Starting with a simple CI run for master. Should be improved in future

addedd github ci actions

---

.github/workflows/myfaces-ci.yml
api/pom.xml
extensions/quarkus/pom.xml
impl/src/test/resources/org/apache/myfaces/config/jsf22-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf23-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf30-faces-config.xml
impl/src/test/resources/org/apache/myfaces/config/jsf40-faces-config.xml
impl/standard-faces-config-base.NavData
parent/pom.xml
pom.xml

Simplify rat config unfortunately we need it twice. Someone added poms with CRLF I need to fix it
You can see the ci build based on github actions is running

ci build fixes

---

impl/src/main/resources/org/apache/myfaces/resource/web-facesconfig_4_0.xsd

Add 3.0 and 4.0 to supported enumerations

---

impl/src/main/java/org/apache/myfaces/application/viewstate/ClientSideStateCacheImpl.java
impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketChannelTokenBuilderBean.java

prefer secureRandom over random

---

impl/src/main/java/org/apache/myfaces/application/viewstate/StateUtils.java
impl/src/test/java/org/apache/myfaces/application/viewstate/CachedStateUtilsDefaultTest.java
impl/src/test/java/org/apache/myfaces/application/viewstate/StateUtilsDefaultTest.java

Update Cryptographic algorithm in StateUtils to a stronger version

MYFACES-4376

---

.github/workflows/myfaces-ci.yml
pom.xml

more relaxed about Readme and *.iml files during rat check

added checkstyle to 3.0.x build

---

.github/workflows/myfaces-ci.yml
impl/src/main/java/org/apache/myfaces/push/cdi/WebsocketChannelTokenBuilderBean.java
pom.xml

more relaxed about Readme and *.iml files during rat check
fixed checkstyle error

added checkstyle to 2.3.x build

---

.github/workflows/myfaces-ci.yml
pom.xml

more relaxed about Readme and *.iml files during rat check

added ci build to 2.3-next

---

.travis.yml

Creating CI workflow for the 2.3.x branch as ready done in other branches.

create travis ci flow for 2.3 branch

---

Jenkinsfile

Adding Jenkins File
Tested on Master. See
-  https://ci-builds.apache.org/job/MyFaces/job/MyFaces%20Pipeline/job/master/
-  https://repository.apache.org/content/repositories/snapshots/org/apache/myfaces/core/myfaces-api/4.0.0-SNAPSHOT/
Subscribe to notifications@myfaces.apache.org for notifications (https://myfaces.apache.org/#/community?id=mailing-lists)

Add jenkinsfile 2.3-next

---

Jenkinsfile

Adding Jenkins File
Tested on Master. See
-  https://ci-builds.apache.org/job/MyFaces/job/MyFaces%20Pipeline/job/master/
-  https://repository.apache.org/content/repositories/snapshots/org/apache/myfaces/core/myfaces-api/4.0.0-SNAPSHOT/
Subscribe to notifications@myfaces.apache.org for notifications (https://myfaces.apache.org/#/community?id=mailing-lists)

Add jenkinsfile to 2.3.x

---

Jenkinsfile

Adding Jenkins File
Tested on Master. See
-  https://ci-builds.apache.org/job/MyFaces/job/MyFaces%20Pipeline/job/master/
-  https://repository.apache.org/content/repositories/snapshots/org/apache/myfaces/core/myfaces-api/4.0.0-SNAPSHOT/
Subscribe to notifications@myfaces.apache.org for notifications (https://myfaces.apache.org/#/community?id=mailing-lists)

Add jenkinsfile 3.0.x

---

Jenkinsfile

added more jdks to jenkins ci build

---

parent/pom.xml
pom.xml

oops, minor typo in https://github.com/apache/myfaces/pull/170 fixed here.

Fix typo in Pom from PR #170

---

.github/workflows/myfaces-ci.yml
ci.md
pom.xml

updated github actions

---

shared/src/main/java/org/apache/myfaces/shared/resource/ResourceImpl.java

cherry-picked this one for 3.0.x

MYFACES-4371 Resources: set cache-control-header instead of expires-header

---

extensions/quarkus/deployment/pom.xml
extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/pom.xml
extensions/quarkus/showcase/README.md
extensions/quarkus/showcase/pom.xml
extensions/quarkus/showcase/src/main/resources/META-INF/web.xml

resolve (MYFACES-4392) Update to quarkus 1.13.0.Final

feat(quarkus): update to quarkus 1.13.0.Final

---

impl/src/main/java/org/apache/myfaces/cdi/util/CDIUtils.java

https://github.com/apache/myfaces/pull/181 caused a compilation error - the util referenced by the code in that PR needs to be backported to 2.2.x

fix 2.2.x compilation error - add util needed by MYFACES-4382

---

impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java
impl/src/test/java/org/apache/myfaces/application/ResourceHandlerImplTest.java

backport of https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4187

backport MYFACES-4187 to 2.2.x

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

https://issues.apache.org/jira/browse/MYFACES-4404

MYFACES-4404 -- Log viewstate string

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
shared/src/main/java/org/apache/myfaces/shared/util/StateUtils.java

Using hashcode to save log space & allow an indicator for a modified viewstate.

Myfaces 4404 2.3.x update

---

impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlSecretRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlTextRendererBase.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlSecretRendererTest.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextRendererTest.java

Issues/2.3-next myfaces-4428 refactor code into encodeBegin HtmlTextRendererBase / HtmlSecretRendererBase
See https://github.com/apache/myfaces/pull/228

Issues/2.3-next myfaces-4428 refactor code into encodeBegin

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlSecretRendererTest.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlSecretRendererBase.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlTextRendererBase.java

MYFACES-4428 - Separate 'begin tag' code from 'end tag' code in HtmlTextRendererBase / HtmlSecretRendererBase
see: https://github.com/apache/myfaces/pull/228

MYFACES-4428 - Separate 'begin tag' code from 'end tag' code in HtmlTextRendererBase / HtmlSecretRendererBase

---

impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4431

Fix NPE - MYFACES-4431

---

impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4431

MYFACES-4431 2.2.x

---

impl/src/main/java/org/apache/myfaces/cdi/JsfArtifactProducer.java
impl/src/main/java/org/apache/myfaces/el/unified/resolver/implicitobject/ImplicitObjectResolver.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4432

MYFACES-4432 / MYFACES-4394- 2.3.x

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlTextareaRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/HtmlTextareaRendererBase.java

MYFACES-4434 - HtmlTextareaRendererBase separate encode end and begin

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java
impl/src/main/java/org/apache/myfaces/lifecycle/clientwindow/ClientConfig.java

[MYFACES-4435](https://issues.apache.org/jira/browse/MYFACES-4435)

MYFACES-4435 - Update Language 2.3-next

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java
impl/src/main/java/org/apache/myfaces/lifecycle/ClientConfig.java

https://issues.apache.org/jira/browse/MYFACES-4435

MYFACES-4435 - Update Language 3.0.x

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java
impl/src/main/java/org/apache/myfaces/lifecycle/clientwindow/ClientConfig.java

https://issues.apache.org/jira/browse/MYFACES-4435

MYFACES-4435 - Update Language 4.0.x

---

api/src/main/java/javax/faces/component/UIForm.java

Backport to fix this issue: https://github.com/primefaces-extensions/primefaces-extensions/issues/799

MYFACES-4283 Backport to 2.2

---

api/src/main/java/javax/faces/component/UIForm.java

MYFACES-4283 Backport to 2.2 Fix Spacing

---

impl/src/main/java/org/apache/myfaces/context/flash/FlashImpl.java
impl/src/main/java/org/apache/myfaces/lifecycle/clientwindow/ClientConfig.java
test/src/main/java/org/apache/myfaces/test/mock/MockServletContext.java

Per: https://github.com/jakartaee/faces/issues/1570#issuecomment-1153486903
Now check the servlet context cookie config value first then defaults to "Strict" if not found.

MYFACES-4417: Cookie SameSite=Strict

---

impl/src/main/java/org/apache/myfaces/cdi/JsfArtifactProducer.java
impl/src/main/java/org/apache/myfaces/el/unified/resolver/implicitobject/ImplicitObjectResolver.java

This was unfortunately missed.  Will be included in the next 3.0.3 release.

MYFACES-4432 - Resolve request object (Ports MYFACES-4394)

---

impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java
impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

Fix for MYFACES-4442: https://issues.apache.org/jira/browse/MYFACES-4442

MYFACES-4442: avoid UnsupportedOperationException

---

api/src/main/java/jakarta/faces/application/StateManagerWrapper.java

https://issues.apache.org/jira/browse/MYFACES-4451
Remove Deprecated constructor in StateManagerWrapper.
The Faces 3.0 Javadoc: https://jakarta.ee/specifications/faces/3.0/apidocs/jakarta/faces/application/statemanagerwrapper
The Faces 4.0 Javadoc: https://jakarta.ee/specifications/faces/4.0/apidocs/jakarta/faces/application/statemanagerwrapper

MYFACES-4451: Remove Deprecated constructor

---

api/src/main/java/jakarta/faces/component/UIData.java

https://issues.apache.org/jira/browse/MYFACES-4452

MYFACES-4452: make getSubIdPattern a private method

---

impl/src/main/java/org/apache/myfaces/util/lang/ClassUtils.java

https://issues.apache.org/jira/browse/MYFACES-4449
Copied API ClassUtils methods to Impl ClassUtils

MYFACES-4449

---

impl/src/main/java/org/apache/myfaces/util/lang/ClassUtils.java

Address previous review comment: https://github.com/apache/myfaces/pull/299#issuecomment-1234131667

MYFACES-4449: Add comments

---

api/src/main/java/jakarta/faces/context/ExternalContextWrapper.java
api/src/main/java/jakarta/faces/render/Renderer.java

https://issues.apache.org/jira/browse/MYFACES-4454

MYFACES-4454

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlLabelRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/CommonPropertyUtils.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4450

2.3.x: MYFACES-4450: Render tabindex for outputLabel

---

impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlLabelRendererTest.java
shared/src/main/java/org/apache/myfaces/shared/renderkit/html/CommonPropertyUtils.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4450

2.2.x: MYFACES-4450: render tabindex for outputLabel; update test

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/CommonPropertyUtils.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlLabelRendererTest.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4450

2.3-next: MYFACES-4450: render tabindex for outputLabel; update test

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/CommonHtmlAttributesUtil.java
impl/src/test/java/org/apache/myfaces/renderkit/html/HtmlLabelRendererTest.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4450

4.0.x: MYFACES-4450: render tabindex for outputLabel; update test

---

api/src/main/java/jakarta/faces/component/_UIWebsocket.java
api/src/main/resources/META-INF/componentClass20.vm

https://issues.apache.org/jira/browse/MYFACES-4457

MYFACES-4457: UIWebSocket.getEventNames fix

---

api/src/main/java/javax/faces/component/_UIWebsocket.java
api/src/main/resources/META-INF/componentClass20.vm

https://issues.apache.org/jira/browse/MYFACES-4457

MYFACES-4457

---

api/pom.xml
impl/pom.xml
parent/pom.xml

https://issues.apache.org/jira/browse/MYFACES-4460
Also removing the import for `javax.servlet.jsp`, `javax.servlet.jsp.tagext`, and `javax.servlet.jsp.jstl.core`

MYFACES-4460: remove JSTL(Tags) dependency

---

impl/src/main/java/org/apache/myfaces/cdi/FacesArtifactProducerExtension.java

https://issues.apache.org/jira/browse/MYFACES-4461

MYFACES-4461: Remove registerCdiProducers checks / Use CDI for implicit objects

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/LambdaMetadataTargetImpl.java

https://issues.apache.org/jira/browse/MYFACES-4465

MYFACES-4465: avoid ClassCastException

---

impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlButtonRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlJavaScriptUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4462
Ported code from 3.0 minus IE support

MYFACES-4462: Generate script tag

---

api/src/main/javascript/META-INF/resources/myfaces/api/faces.js

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4464

MYFACES-4464: resolve js error

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js

https://issues.apache.org/jira/browse/MYFACES-4467
originally done under MYFACES-4390

MYFACES-4467 Process multiple files via ajax:

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlStylesheetRenderer.java

https://issues.apache.org/jira/browse/MYFACES-4470

MYFACES-4470: Render text/css only on HTML4

---

api/src/main/java/jakarta/faces/component/_UISelectItemGroup.java
api/src/main/java/jakarta/faces/component/_UISelectItemGroups.java
impl/src/main/java/org/apache/myfaces/view/facelets/tag/faces/core/CoreLibrary.java
impl/src/main/java/org/apache/myfaces/view/facelets/tag/faces/core/SelectItemGroupHandler.java
impl/src/test/java/org/apache/myfaces/view/facelets/tag/faces/html/SelectOneItemGroupTest.java
impl/src/test/java/org/apache/myfaces/view/facelets/tag/faces/html/SelectOneItemGroupTestBean.java
impl/src/test/resources/org/apache/myfaces/view/facelets/tag/faces/html/selectOneItemGroup.xhtml

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4468
Needed to remove COMPONENT_FAMILY for TCK signature results.
```
[javatest.batch] Added Fields
[javatest.batch] ------------
[javatest.batch]
[javatest.batch] jakarta.faces.component.UISelectItemGroups: field public final static java.lang.String jakarta.faces.component.UISelectItemGroups.COMPONENT_FAMILY = "jakarta.faces.SelectItemGroups"
```

MYFACES-4468: Implement selectItemGroup

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java
impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

https://issues.apache.org/jira/browse/MYFACES-4447
Once we merge this I'll start working on backporting this fix where necessary.

MYFACES-4447: avoid UnsupportedOperationException

---

api/src/main/java/jakarta/faces/convert/NumberConverter.java

https://issues.apache.org/jira/browse/MYFACES-4474

MYFACES-4474: remove setType validation

---

impl/src/main/java/org/apache/myfaces/view/facelets/compiler/DoctypeInstruction.java

https://issues.apache.org/jira/browse/MYFACES-4475

MYFACES-4475: remove space before closing >

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Dom.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/_EvalHandlers.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/_Runtime.js

nonce handling ported over from 2.3-next branch.
All the tests pass which passed before the fix, the new nonce tests pass as well!

https://issues.apache.org/jira/browse/MYFACES-4479:

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/TagAttributeImpl.java

MYFACES-4480: 3.0.x: Fix NPE TagAttributeImpl#getBoolean

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/TagAttributeImpl.java

MYFACES-4480: 2.2.x: Fix NPE TagAttributeImpl#getBoolean

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/TagAttributeImpl.java

MYFACES-4480: 2.3-next: Fix NPE TagAttributeImpl#getBoolean

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/TagAttributeImpl.java

MYFACES-4480: 2.3.x: Fix NPE TagAttributeImpl#getBoolean

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/TagAttributeImpl.java

MYFACES-4480: 4.0.x: Fix NullPointerException in TagAttributeImpl#getBoolean

---

impl/src/main/java/org/apache/myfaces/view/facelets/tag/composite/CompositeResourceLibrary.java

https://issues.apache.org/jira/browse/MYFACES-4484

MYFACES-4484: Add forward slash to composite namespace

---

impl/src/main/java/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java

https://issues.apache.org/jira/browse/MYFACES-4486

MYFACES-4486: don't update model

---

api/src/main/resources/META-INF/componentClass20.vm

https://issues.apache.org/jira/browse/MYFACES-4444

MYFACES-4444: Faces 4.0 component deprecations

---

api/src/main/java/javax/faces/model/SelectItem.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/SelectItemsUtils.java

https://issues.apache.org/jira/browse/MYFACES-4492

MYFACES-4492: don't NPE when no label is set

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImplEventManager.java

https://issues.apache.org/jira/browse/MYFACES-4495

MYFACES-4495: Throw NPE  when necessary

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java

https://issues.apache.org/jira/browse/MYFACES-4495

MYFACES-4495: Throw NPE when necessary

---

api/src/main/java/jakarta/faces/context/PartialResponseWriter.java

https://issues.apache.org/jira/browse/MYFACES-4501

MYFACES-4501: Add xml preamble to every ajax response

---

impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java

https://issues.apache.org/jira/browse/MYFACES-4500

MYFACES-4500: throw ISE in ajax request if redirect is already completed

---

api/src/main/java/javax/faces/component/UIComponent.java

Fixing localized composite behaviour (2.3.x)

---

api/src/main/java/javax/faces/component/UIComponent.java

Fixing localized properties behaviour (2.3-next)

---

api/src/main/java/jakarta/faces/component/UIComponent.java

Fixing localized composite behaviour (main)

---

api/src/main/java/jakarta/faces/component/UIComponent.java

https://issues.apache.org/jira/browse/MYFACES-4502

MYFACES-4502: add bindings map back

---

impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4504

MYFACES-4504: check isEmpty() to avoid UnsupportedOperationException

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js

https://issues.apache.org/jira/browse/MYFACES-4499: Fix from

---

impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopeContext.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4507

MYFACES-4507: Create contextual storage if it doesn't exist for flow

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4503

MYFACES-4503: use ELManager.getExpressionFactory()

---

api/src/main/java/jakarta/faces/convert/NumberConverter.java
impl/src/test/java/jakarta/faces/convert/NumberConverterTest.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4508

MYFACES-4508: Handle Integer Only Parse Position

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js

Small follow-up to 4499 and 4498. 
https://github.com/apache/myfaces/pull/394
https://github.com/apache/myfaces/pull/392

4.0.0: Fix undefined variable errors

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/api/faces.js

Fix for the breaking TCK-790 issue, 4.0 old codebase (new codebase PR already has them in)

Fix for MYFACES-4511

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/api/jsf.js

2.3 next: Fix for MYFACES-4511

---

impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java

https://issues.apache.org/jira/browse/MYFACES-4512

MYFACES-4512: avoid NPE in createView

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js

https://issues.apache.org/jira/browse/MYFACES-4521 fix

---

impl/src/main/java/org/apache/myfaces/application/FacesServletMappingUtils.java

https://issues.apache.org/jira/browse/MYFACES-4524

MYFACES-4524: Generate Correct Resource Path in Non-Faces Requests

---

api/src/main/javascript/META-INF/resources/myfaces/api/jsf.js
impl/src/main/java/org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.java

Fix for https://issues.apache.org/jira/browse/MYFACES-4040

Fix for https://issues.apache.org/jira/browse/MYFACES-4040

---

api/src/main/javascript/META-INF/resources/myfaces/api/jsf.js

accidentally comitted wrong namespace

https://issues.apache.org/jira/browse/MYFACES-4040

---

impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java

https://issues.apache.org/jira/browse/MYFACES-4527

MYFACES-4527: Check for existing writer before creating one

---

.gitignore
pom.xml

I use Visual Studio Code as my primary IDE, and this would make it easier for development.

Ignore .vscode

---

.gitignore
api/src/main/java/javax/faces/context/PartialResponseWriter.java
impl/src/main/java/org/apache/myfaces/context/servlet/PartialViewContextImpl.java
impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopedContextImpl.java
impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
pom.xml
shared/src/main/java/org/apache/myfaces/shared/application/FacesServletMappingUtils.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4527
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4524
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4501
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4500
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4507

Port various fixes to 2.3.x

---

.gitignore
api/src/main/java/javax/faces/context/PartialResponseWriter.java
api/src/main/java/javax/faces/convert/NumberConverter.java
impl/src/main/java/org/apache/myfaces/application/FacesServletMappingUtils.java
impl/src/main/java/org/apache/myfaces/context/servlet/PartialViewContextImpl.java
impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopedContextImpl.java
impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
impl/src/test/java/javax/faces/convert/NumberConverterTest.java
pom.xml

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4527
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4524
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4501
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4500
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4507
Also includes: 
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4508

Port fixes to 2.3 next

---

.gitignore
api/src/main/java/jakarta/faces/context/PartialResponseWriter.java
impl/src/main/java/org/apache/myfaces/context/servlet/PartialViewContextImpl.java
impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopedContextImpl.java
impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
pom.xml
shared/src/main/java/org/apache/myfaces/shared/application/FacesServletMappingUtils.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4527
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4524
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4501
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4500
https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4507

Port fixes to 3.0.x

---

api/src/main/java/org/apache/myfaces/core/api/shared/SharedRendererUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/RendererUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlCheckboxRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/SelectItemsUtils.java

https://issues.apache.org/jira/browse/MYFACES-4529
I may also add a test for SelectItemGroup -  I only tested locally.
TCK: Output:
http://localhost:9080/test-faces23-uiinput/spec1422.xhtml  
```
<span id="form:result">[ONE, TWO, THREE][null, 1, 2, 3, 4.5, 6.7, 8.9]</span>
```
Matches the expected result (and all asserts in the bean pass):
https://github.com/jakartaee/faces/blob/4.0.1/tck/faces23/uiinput/src/test/java/ee/jakarta/tck/faces/test/javaee8/uiinput/Spec1422IT.java#L83
```
assertTrue(page.getHtmlElementById("form:result").asNormalizedText().equals("[ONE, TWO, THREE][null, 1, 2, 3, 4.5, 6.7, 8.9]"));
```

MYFACES-4529: Improve UISelectMany's Collection Support

---

impl/src/main/java/org/apache/myfaces/config/annotation/CdiAnnotationProviderExtension.java

https://issues.apache.org/jira/browse/MYFACES-4534

MYFACES-4534: Check for null in CdiAnnotationProviderExtension#release

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

Follow up to https://issues.apache.org/jira/browse/MYFACES-4514

MYFACES-4514 -- follow up, do not write empty string for onchange

---

impl/src/main/java/org/apache/myfaces/component/search/MyFacesSearchExpressionHints.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlAjaxBehaviorRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.java
impl/src/test/java/org/apache/myfaces/view/facelets/tag/jsf/html/DefaultHtmlDecoratorTestCase.java
shared-public/src/main/java/org/apache/myfaces/shared/util/StringUtils.java

Crossporting the fixes 
from 2.3-next and main

https://issues.apache.org/jira/browse/MYFACES-4040: 

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.java

merging in smaller code improvements from 3.0

https://issues.apache.org/jira/browse/MYFACES-4040:

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/QuarkusFacesInitializer.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/application/QuarkusApplication.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/producer/ManagedPropertyBeanCreator.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/scopes/QuarkusFacesScopeContext.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/scopes/QuarkusFlowScopedContext.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/scopes/QuarkusViewScopeContext.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/scopes/QuarkusViewTransientScopeContext.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/spi/QuarkusCdiELResolver.java
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/spi/QuarkusELResolverBuilder.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/CarService.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/FileView.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/InputController.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/LazyView.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MethodHandleELResolverBean.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MyBacking.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/MyValidator.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/SocketView.java

@tandraschko Quarkus 3 in beta for Jakarta EE 10.  I tried to upgrade but there are some MyFaces JSF changes that are above my level of understanding.
Here is how far I fgot...

Quarkus 3 Preview

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/showcase/pom.xml
extensions/quarkus/showcase/src/test/java/org/apache/myfaces/core/extensions/quarkus/showcase/QuarkusMyFacesShowcaseTest.java
impl/src/main/java/org/apache/myfaces/cdi/view/ViewScopeEventListenerBridge.java
impl/src/main/java/org/apache/myfaces/cdi/view/ViewScopeExtension.java
pom.xml

@tandraschko  I got it all working!
Quarkus did not like the ViewScopedEventListener.Bridge being an inner scoped Application scoped static bean. I moved it into its own normal class and then Quarkus was able to discover it!

Quarkus 3 support

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Quarkus config missing resources

Quarkus config missing resources

---

impl/src/main/java/org/apache/myfaces/util/WebXmlParser.java

https://issues.apache.org/jira/browse/MYFACES-4540

MYFACES-4540: add doPriv for url.openStream()

---

impl/src/main/java/org/apache/myfaces/flow/cdi/FlowScopeContext.java

https://issues.apache.org/jira/browse/MYFACES-4542

MYFACES-4542 - fix outbound-parameters not passed to nested flows

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

https://issues.apache.org/jira/browse/MYFACES-4544

MYFACES-4544: Do not set disabled inputs as submitted values

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Dom.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js

Fixes the reported not working double include check

https://issues.apache.org/jira/browse/MYFACES-4532: Fix for MYFACES-4532

---

integration-tests/ajax/src/test/resources/arquillian.xml
integration-tests/autoLookupExpressionFactoryWithoutJSP/src/test/resources/arquillian.xml
integration-tests/automaticExtensionlessMapping/src/test/resources/arquillian.xml
integration-tests/exactMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMappingDisabled/src/test/resources/arquillian.xml
integration-tests/pom.xml
integration-tests/protectedViews/src/test/resources/arquillian.xml

arquillian try to execute the LICENSE.chromedriver file. Need to stick to the 108 version

build(ci): chromedriver version 109.0.5414.25 contains two files.

---

.github/workflows/myfaces-ci.yml
Jenkinsfile
README.md
integration-tests/ajax/readme.txt
integration-tests/ajax/src/test/java/org/apache/myfaces/core/integrationtests/ajax/IntegrationTest.java
integration-tests/ajax/src/test/resources/arquillian.xml
integration-tests/autoLookupExpressionFactoryWithoutJSP/src/test/resources/arquillian.xml
integration-tests/automaticExtensionlessMapping/src/test/resources/arquillian.xml
integration-tests/exactMapping/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/exactMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMapping/src/test/resources/arquillian.xml
integration-tests/faceletToXhtmlMappingDisabled/src/test/resources/arquillian.xml
integration-tests/pom.xml
integration-tests/protectedViews/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/protectedViews/src/test/resources/arquillian.xml

remove graphene it's only supporting an old version of selenium. 
update selenium and tomcat versions.
minor fixes

build(ci): update arquillian drone to 3.0.0-alpha.7 to support latest chromeDriver package.

---

.github/workflows/codeql-analysis.yml
README.md
extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/spi/QuarkusInjectionProvider.java
parent/src/site/xdoc/release-checklist.xml

build: rename master to main

---

impl/src/main/java/org/apache/myfaces/el/FacesELContext.java

https://issues.apache.org/jira/browse/MYFACES-4547

MYFACES-4547: return new DefaultVariableMapper if variableMapper is null

---

api/src/main/java/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorUtils.java

I don't know where the documentation is.  Is it another project on GitHub?
https://issues.apache.org/jira/browse/MYFACES-4548

MYFACES-4548 4.0: org.apache.myfaces.USE_LAMBDA_METAFACTORY default false

---

impl/src/main/java/org/apache/myfaces/el/unified/FacesELContext.java

https://issues.apache.org/jira/browse/MYFACES-4547

MYFACES-4547: return new DefaultVariableMapper if _variableMapper is null

---

impl/src/main/java/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java

https://issues.apache.org/jira/browse/MYFACES-4550

MYFACES-4550: throw exception if f:validateWholeBean is misplaced

---

impl/src/main/java/org/apache/myfaces/config/impl/FacesConfigUnmarshallerImpl.java

https://issues.apache.org/jira/browse/MYFACES-4552

MYFACES-4552 Fix correct attribute

---

api/src/main/java/jakarta/faces/component/UISelectOne.java
impl/src/main/java/org/apache/myfaces/renderkit/RendererUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

https://issues.apache.org/jira/browse/MYFACES-4551
Various scenarios tested in the TCK, see: https://github.com/jakartaee/faces/blob/c6d7d879065056978d74e5f486847fb203606203/tck/faces23/uiinput/src/main/webapp/spec329.xhtml 
This TCK test has been a pain to debug in our impl and to understand. I've added comments and concerns for clarity. Thanks.

MYFACES-4551: Allow group validation for uiselectone elements

---

api/src/main/java/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorUtils.java

https://issues.apache.org/jira/browse/MYFACES-4554

MYFACES-4554: log FINEST rather than INFO

---

api/src/main/java/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorUtils.java

Revert "MYFACES-4554: log FINEST rather than INFO"

---

impl/pom.xml
impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java

Fix for https://issues.apache.org/jira/browse/MYFACES-4553
Details can be found in the comment in the JIRA above.

MYFACES-4553: Fix WELD-001303 By Forcing Flow Transition Earlier 

---

README.md
api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_FormDataRequest.js
impl/pom.xml
impl/src/main/java/org/apache/myfaces/application/NavigationHandlerImpl.java
impl/src/main/java/org/apache/myfaces/context/servlet/RequestParameterMap.java
impl/src/main/java/org/apache/myfaces/el/resolver/LambdaBeanELResolver.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
impl/src/main/java/org/apache/myfaces/util/ViewNamespaceUtils.java
test/src/main/java/org/apache/myfaces/test/mock/MockApplication10.java

By suggestion of @tandraschko he wants to work on a better solution for the issue!
Providing a pull request against main for the js only changes, so that he can take over with a hopefully better solution to the issue!

MYFACES-4533: JS only for a better solution

---

api/src/main/java/jakarta/faces/component/UISelectOne.java

The original fix for MYFACES-4551 ( #492) created some regressions, so I'm adding a follow up patch here.
The issue was with where the value expression was placed. 
For example, if multiple selectOneRadio elements are used and the the VE is in first element, and spec says to use the first one in the group with a VE ([see here -- group](https://jakarta.ee/specifications/faces/4.0/renderkitdoc/HTML_BASIC/jakarta.faces.SelectOnejakarta.faces.Radio.html)). If someone picked the second radio button (Value2),  [our code sets the submitted value on the first element with the VE.](https://github.com/apache/myfaces/blob/6bf7e9d86d881165d79f39927d3abd2d80bc76ff/impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java#L372-L379) However, with my last fix, during validation of …

MYFACES-4551 follow up to fix radio selection

---

impl/src/main/java/org/apache/myfaces/cdi/FacesArtifactProducer.java

https://issues.apache.org/jira/browse/MYFACES-4559

MYFACES-4559: application implicit object fix

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Saw this deprecation warning and fixed it.

Quarkus update deprecated profile handling

---

impl/src/main/java/org/apache/myfaces/application/DefaultResourceHandlerSupport.java

Fix for https://issues.apache.org/jira/browse/MYFACES-4565, accidentally a temp file resource loader was introduced when there should be none!

https://issues.apache.org/jira/browse/MYFACES-4565

---

api/src/client/development.md
api/src/client/package-lock.json
api/src/client/package.json
api/src/client/readme.md
api/src/client/tsconfig-typedoc.json
api/src/client/typescript/faces/@types/definitions/index.d.ts
api/src/client/typescript/faces/api/_api.ts
api/src/client/typescript/faces/impl/AjaxImpl.ts

This is the fix for https://issues.apache.org/jira/browse/MYFACES-4567, the jsdoc generation works again, also some of the jsdocs are improved.
I will merge this fix post RC5!

Fix for https://issues.apache.org/jira/browse/MYFACES-4567

---

impl/src/main/java/org/apache/myfaces/resource/FacesJSResourceLoader.java

https://issues.apache.org/jira/browse/MYFACES-4570

MYFACES-4570: fix NPE

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
impl/src/main/java/org/apache/myfaces/util/WebXmlParser.java

1. register web.xml
1. register all Exceptions found in web.xml for reflection (always include ViewExpiredException no matter what)
Since there is no ExternalContext but i needed to use WebXmlParser I made as little changes as possible to allow it to be used in the Deployment processor.

MYFACES-4573: 4.0 Quarkus native exception registration

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
impl/src/main/java/org/apache/myfaces/util/WebXmlParser.java

1. register web.xml
2. regsiter all Exceptions found in web.xml for reflection

MYFACES-4573: Quarkus native exception registration

---

impl/src/main/java/org/apache/myfaces/util/DebugUtils.java

https://issues.apache.org/jira/browse/MYFACES-4563?

MYFACES-4563: ignore viewMap in debug to avoid OOM

---

api/src/client/typescript/faces/api/_api.ts
api/src/client/typescript/faces/impl/AjaxImpl.ts
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.java

There was an accidental typo of onOnDomReady this now has been renamed to onDomReady

MYFACES-4575: onDomReady rename

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Quarkus 4.0 Refactor

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

This is just one last pass of me looking at the code and a little house cleaning and fixing a RuntimeIntializer that I was doing 2 different ways.

Quarkus 2.3 Refactor

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Similar to other scope holders added to Quarkus

MYFACES-4580: Quarkus ClientWindowScopeContextualStorageHolder

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Based on findings: https://github.com/quarkusio/quarkus/issues/32337

MYFACES-4598: Quarkus do not register ClientProxy

---

extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/showcase/pom.xml

Just some final cleanup before 4.0.1 release

Quarkus pom.xml updates

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Revert "MYFACES-4598: Quarkus do not register ClientProxy"

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Revert "MYFACES-4598: 2.3next Quarkus do not register ClientProxy"

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/showcase/pom.xml

@volosied this is 4.0 only so no changes for 2.3-next 😄 
GraalVM was spitting out these warnings:
```
Warning: Could not resolve jakarta.faces.application.Application_ClientProxy for reflection configuration. Reason: java.lang.ClassNotFoundException: jakarta.faces.application.Application_ClientProxy.
Warning: Could not resolve jakarta.faces.application.FacesMessage$Severity_ClientProxy for reflection configuration. Reason: java.lang.ClassNotFoundException: jakarta.faces.application.FacesMessage$Severity_ClientProxy.
Warning: Could not resolve jakarta.faces.application.NavigationHandler_ClientProxy for reflection configuration. Reason: java.lang.ClassNotFoundException: jakarta.faces.application.NavigationHandler_ClientProxy.
Warning: Could not resolve …
```

MYFACES-4598: 4.0 Quarkus reduce WARNING noise

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

cc @tandraschko you were right it then was having reflection issues with Converters.

MYFACES-4598: Quarkus put "jakarta.faces" proxies back in

---

impl/src/main/java/org/apache/myfaces/application/ApplicationFactoryImpl.java
impl/src/main/java/org/apache/myfaces/config/FacesConfigurator.java
impl/src/main/java/org/apache/myfaces/config/RuntimeConfig.java
impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/main/java/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
impl/src/main/java/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
impl/src/main/java/org/apache/myfaces/util/Purgeable.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4469

Apply MYFACES-4469 to 2.3-next

---

impl/src/main/java/org/apache/myfaces/application/ApplicationFactoryImpl.java
impl/src/main/java/org/apache/myfaces/config/FacesConfigurator.java
impl/src/main/java/org/apache/myfaces/config/RuntimeConfig.java
impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/main/java/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
impl/src/main/java/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
impl/src/main/java/org/apache/myfaces/util/Purgeable.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4469

Apply MYFACES-4469 to 2.3

---

impl/src/main/java/org/apache/myfaces/application/ApplicationFactoryImpl.java
impl/src/main/java/org/apache/myfaces/config/FacesConfigurator.java
impl/src/main/java/org/apache/myfaces/config/RuntimeConfig.java
impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/main/java/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
impl/src/main/java/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
impl/src/main/java/org/apache/myfaces/util/Purgeable.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4469

Apply MYFACES-4469 to 3.0.x

---

impl/src/main/java/org/apache/myfaces/application/ApplicationFactoryImpl.java
impl/src/main/java/org/apache/myfaces/config/FacesConfigurator.java
impl/src/main/java/org/apache/myfaces/config/RuntimeConfig.java
impl/src/main/java/org/apache/myfaces/context/servlet/FacesContextImplBase.java
impl/src/main/java/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
impl/src/main/java/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
impl/src/main/java/org/apache/myfaces/util/Purgeable.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4469

Apply MYFACES-4469 to 2.2.x

---

impl/src/main/java/org/apache/myfaces/webapp/AbstractFacesInitializer.java

https://issues.apache.org/jira/browse/MYFACES-4604

MYFACES-4604: Update f:websocket integration message

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_AjaxRequestQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_FormDataRequest.js

Also adds the naming container fixes for 3.0 to the 2.3x branch! (MYFACES-4533)

MYFACES-4606: Fix the missing issuing element

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_AjaxRequestQuirks.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js

Fixes the issue with the missing submitting element

Fix for: MYFACES-4606

---

parent/pom.xml

https://issues.apache.org/jira/browse/MYFACES-4607

Update commons digester to 2.1 - 2.2.x

---

parent/pom.xml

https://issues.apache.org/jira/browse/MYFACES-4607

Update commons digester to 2.1 - 3.0.x

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js

Fix for identifier postfix number to start with 1

MYFACES-4605

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxResponse.js

Fix for identifier postfix number to start with 1

https://issues.apache.org/jira/browse/MYFACES-4605

---

impl/src/main/java/org/apache/myfaces/view/facelets/ViewPoolProcessor.java

https://issues.apache.org/jira/browse/MYFACES-4611

MYFACES-4611: Avoid NPE when root is null

---

api/src/main/java/jakarta/faces/component/UIData.java
api/src/main/java/jakarta/faces/component/UIViewRoot.java
impl/src/main/java/org/apache/myfaces/application/viewstate/StateUtils.java
impl/src/main/java/org/apache/myfaces/component/validate/WholeBeanValidator.java
impl/src/main/java/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java
impl/src/main/java/org/apache/myfaces/config/FacesConfigurator.java
impl/src/main/java/org/apache/myfaces/context/ExceptionHandlerUtils.java
impl/src/main/java/org/apache/myfaces/lifecycle/LifecycleImpl.java
impl/src/main/java/org/apache/myfaces/lifecycle/RestoreViewExecutor.java
impl/src/main/java/org/apache/myfaces/renderkit/RendererUtils.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlCompositeComponentRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlFormatRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlRenderKitImpl.java
impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
impl/src/main/java/org/apache/myfaces/util/MessageUtils.java
impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
impl/src/main/java/org/apache/myfaces/view/facelets/compiler/CompilationManager.java
impl/src/main/java/org/apache/myfaces/view/facelets/compiler/FaceletsCompilerSupport.java
impl/src/main/java/org/apache/myfaces/view/facelets/el/ContextAwareExceptionWrapper.java
impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java
impl/src/test/java/org/apache/myfaces/application/ViewHandlerImplTest.java

Next to fixing "occured -> occurred", I also tried to improve the capitalization. The correct capitalization is not always clear however, as sometimes a normal word which would be all lower letters is also an object name (like "Converter"). So in doubt I left these as they were.

MYFACES-4621 Improve spelling

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

MYFACES-4626: Quarkus handle Session attribute map

MYFACES-4626: Quarkus handle Session attribute map

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

https://issues.apache.org/jira/browse/MYFACES-4628
Waiting for TCK run before merging....

MYFACES-4628

---

api/src/main/java/jakarta/faces/application/StateManager.java
impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java

for `https://github.com/jakartaee/faces/issues/1829`

Spec 1829 : Deprecate full state saving (FSS)

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java

Look for java:comp/env/BeanManager if request for… java:comp/BeanManager fails rather than if it succeeds

Fix for MYFACES-4633

---

impl/src/main/java/org/apache/myfaces/config/impl/element/AttributeImpl.java

Check class variable against null rather than passed parameter

Fix MYFACES-4634

---

impl/src/main/java/org/apache/myfaces/config/impl/element/AttributeImpl.java

Check class variable against null rather than passed parameter

Fix MYFACES-4634 (2.3-next branch)

---

impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java

MYFACES-4633 (4.0 branch)

---

impl/src/main/java/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java

Fix MYFACES-4628 - 4.0 branch

---

impl/src/main/java/org/apache/myfaces/view/facelets/PartialStateManagementStrategy.java

https://issues.apache.org/jira/browse/MYFACES-4623

MYFACES-4623 (4.0.x) : Check for duplicate IDs to avoid DuplicateIdException

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/frameworkBase/_ext/shared/StandardInits.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts
api/src/client/webpack.config.ts

Apply MYFACES-4606  follow up and MYFACES-4630 to 4.0.x

---

impl/src/main/java/org/apache/myfaces/view/facelets/component/UIRepeat.java
impl/src/test/java/org/apache/myfaces/view/facelets/component/UIRepeatTest.java

`https://github.com/jakartaee/faces/issues/1263`
I used UIData as a reference so there's a lot of overlap. 5.0 can address the code duplication.

Spec 1263:  Add rowStatePreserved property to UIRepeat 

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/frameworkBase/_ext/shared/StandardInits.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts

Fix for MyFaces 4606, checkboxes and radio buttons are not appended automatically if unchecked!

MYFACES-4606

---

README.md
api/pom.xml
assembly/pom.xml
bundle/pom.xml
extensions/pom.xml
extensions/quarkus/deployment/pom.xml
extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/showcase/pom.xml
impl/pom.xml
integration-tests/ajax/pom.xml
integration-tests/autoLookupExpressionFactoryWithoutJSP/pom.xml
integration-tests/automaticExtensionlessMapping/pom.xml
integration-tests/exactMapping/pom.xml
integration-tests/faceletToXhtmlMapping/pom.xml
integration-tests/faceletToXhtmlMappingDisabled/pom.xml
integration-tests/pom.xml
integration-tests/protectedViews/pom.xml
parent/pom.xml
pom.xml
test/pom.xml

Please review to ensure I caught all references.

Update main to 5.0

---

impl/src/main/java/org/apache/myfaces/view/facelets/component/UIRepeat.java
impl/src/test/java/org/apache/myfaces/view/facelets/tag/ui/RepeatTestCase.java
impl/src/test/resources/org/apache/myfaces/view/facelets/tag/ui/ui_repeat_model_step.xhtml
impl/src/test/resources/org/apache/myfaces/view/facelets/tag/ui/ui_repeat_offset.xhtml

MYFACES-4618: 5.0: ui:repeat clarification on attributes, such as offset and size

Faces 5.0: MYFACES-4618:  ui:repeat clarification on attributes, such as offset and size

---

impl/src/main/java/org/apache/myfaces/view/facelets/PartialStateManagementStrategy.java
integration-tests/myfaces4623/pom.xml
integration-tests/myfaces4623/src/main/java/org/apache/myfaces/core/integrationtests/Bean.java
integration-tests/myfaces4623/src/main/java/org/apache/myfaces/core/integrationtests/CustomComponent.java
integration-tests/myfaces4623/src/main/webapp/WEB-INF/beans.xml
integration-tests/myfaces4623/src/main/webapp/WEB-INF/faces-config.xml
integration-tests/myfaces4623/src/main/webapp/WEB-INF/web.xml
integration-tests/myfaces4623/src/main/webapp/index.xhtml
integration-tests/myfaces4623/src/main/webapp/resources/default/js/test.js
integration-tests/myfaces4623/src/test/java/org/apache/myfaces/core/integrationtests/IntegrationTest.java
integration-tests/myfaces4623/src/test/resources/arquillian.xml
integration-tests/pom.xml

Fix and test working successfully: 
`[2023-10-27 14:45:02] [autobuild] [INFO] Apache MyFaces Core 5.0 - Integration Tests - myfaces4623 SUCCESS [  7.393 s]`

Fix Myfaces 4623 & Add Test for 5.0.x

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/util/FileUtils.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts

Fix for myfaces 4638, inlcuding new unit test!

https://issues.apache.org/jira/browse/MYFACES-4638:

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/xhrCore/RequestParamsTest.spec.ts
api/src/client/typescript/mona_dish/AssocArray.ts

https://issues.apache.org/jira/browse/MYFACES-4640:

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/xhrCore/RequestParamsTest.spec.ts
api/src/client/typescript/mona_dish/AssocArray.ts

https://issues.apache.org/jira/browse/MYFACES-4640

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/_util/_Lang.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js

Fix for MyFaces 4606, checkboxes and radio buttons are not appended automatically if unchecked!

Follow up on https://issues.apache.org/jira/browse/MYFACES-4606

---

api/src/main/java/jakarta/faces/annotation/View.java
impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java

If this looks good, I can create it for 5.0

MYFACES-4644 [4.1] Enable extensionless requests for programmatic views

---

impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java

fixes https://issues.apache.org/jira/browse/MYFACES-4644

MYFACES-4644 [4.0] Enable extensionless requests for programmatic views

---

api/src/main/java/jakarta/faces/validator/ValidatorException.java
impl/src/test/java/jakarta/faces/validator/ValidatorExceptionTest.java

Backport MYFACES-4646 to 4.1.x

---

api/src/main/java/jakarta/faces/validator/ValidatorException.java
impl/src/test/java/jakarta/faces/validator/ValidatorExceptionTest.java

See https://github.com/apache/myfaces/pull/653 for original PR

Backport MYFACES-4646 to 4.0.x

---

api/src/main/java/javax/faces/validator/ValidatorException.java
api/src/test/java/javax/faces/validator/ValidatorExceptionTest.java

See https://github.com/apache/myfaces/pull/653 for original PR

Backport MYFACES-4646 to 2.3.x

---

parent/pom.xml

Fixes ConcurrentModificationException trying to build locally.

MYFACES-4581: Felix 5.1.8

---

extensions/quarkus/pom.xml

Long Term Release version recommended by Quarkus

4.0: Quarkus LTS 3.2.9 Final

---

impl/src/main/java/org/apache/myfaces/push/cdi/PushContextImpl.java

Fix NPE when user does not have active channel (ie leave page with connected channel)

MYFACES-4647  fix NPE when the user does not have an active channel

---

impl/src/main/java/org/apache/myfaces/push/cdi/PushContextImpl.java

unifying behaviour of send method with / without user specifying

MYFACES-4648 send without specifying user returns emptySet instead of Exception

---

api/src/main/java/jakarta/faces/component/UIViewAction.java
impl/src/main/resources/META-INF/myfaces_facelet_core20.vm

Spec Issue 1811

---

api/src/main/java/jakarta/faces/application/ViewHandler.java

https://issues.apache.org/jira/browse/MYFACES-4651

Spec 1828 - Remove facelets.* Context Parameter Aliases

---

impl/src/main/java/org/apache/myfaces/cdi/util/CDIUtils.java
impl/src/main/java/org/apache/myfaces/cdi/wrapper/FacesValidatorCDIWrapper.java

https://issues.apache.org/jira/browse/MYFACES-4655

MYFACES-4655 fix resolving of FacesValidators without value

---

impl/src/main/java/org/apache/myfaces/webapp/MyFacesContainerInitializer.java

https://issues.apache.org/jira/browse/MYFACES-4657

MYFACES-4657: Fix NPE Caused by null ClassName [4.1]

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/ImplTest.spec.ts

https://issues.apache.org/jira/browse/MYFACES-4658: Fix and new test …, also  npm audit fix performed

MYFACES-4658 [4.0] 

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/ImplTest.spec.ts

https://issues.apache.org/jira/browse/MYFACES-4658:

MYFACES-4658 [4.1]

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/ImplTest.spec.ts

https://issues.apache.org/jira/browse/MYFACES-4658: Fix and new test also  npm audit fix performed

MYFACES-4658 [5.0]

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

MYFACES-4659: 2.3 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

MYFACES-4659: 2.3 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

MYFACES-4659: 3.0 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

MYFACES-4659: 3.0 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

MYFACES-4659: 2.3-next Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

MYFACES-4659: 2.3-next Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java

MYFACES-4659: 4.0 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

MYFACES-4659: 4.0 Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

---

impl/src/main/java/org/apache/myfaces/config/webparameters/MyfacesConfig.java

MYFACES-4659: Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

MYFACES-4659: Invert AUTOCOMPLETE_OFF_VIEW_STATE config param

---

impl/src/main/conf/META-INF/standard-faces-config-base.xml

Found via 4.1 TCK Testing
https://issues.apache.org/jira/browse/MYFACES-4664

Make the UUID Converter Implicit

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlHeadRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlBodyRendererBase.java
impl/src/main/java/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguageStrategy.java

https://issues.apache.org/jira/browse/MYFACES-4662
https://issues.apache.org/jira/browse/MYFACES-4664

MYFACES-4662 + Spec 1760

---

impl/src/main/java/org/apache/myfaces/push/Json.java
impl/src/test/java/org/apache/myfaces/push/JsonEncodingTest.java

https://issues.apache.org/jira/browse/MYFACES-4637
Without using a new dependency, this may be the best we can do.
I added a single test case for some basic verification.

MYFACES-4637: Encode Java Records to JSON

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/FaceletView.java

This fixes the issue and addes a showcase example so you can go to http://localhost:8080/facelet.

MYFACES-4668: 4.1 Quarkus add programmatic views

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

MYFACES-4668: 4.0 Quarkus add programmatic views

MYFACES-4668: 4.0 Quarkus add programmatic views

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java
extensions/quarkus/showcase/src/main/java/org/apache/myfaces/core/extensions/quarkus/showcase/view/FaceletView.java

MYFACES-4668: 5.0 Quarkus add programmatic views

MYFACES-4668: 5.0 Quarkus add programmatic views

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/PushImpl.ts

Socket update, via upstream code

https://issues.apache.org/jira/browse/MYFACES-4671:

---

extensions/quarkus/pom.xml
extensions/quarkus/runtime/pom.xml
extensions/quarkus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/quarkus/showcase/pom.xml
extensions/quarkus/showcase/src/main/resources/META-INF/web.xml

MYFACES-4673: 5.0 Quarkus 3.8 LTS

MYFACES-4673: 5.0 Quarkus 3.8 LTS

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js

FormData handling not properly working on old code and new browsers!

https://issues.apache.org/jira/browse/MYFACES-4672:

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/core/Const.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/xhrCore/EventTests.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest_23.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts

https://issues.apache.org/jira/browse/MYFACES-4676:

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts

MYFACES-4679

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/core/Impl.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxRequest.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_AjaxRequestLevel2.js
api/src/main/javascript/META-INF/resources/myfaces/_impl/xhrCore/_ExtAjaxRequest.js

backport of the fixes from 4.0

https://issues.apache.org/jira/browse/MYFACES-4679:

---

impl/src/main/java/org/apache/myfaces/view/facelets/compiler/CompilationManager.java

https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4681

MYFACES-4681

---

api/src/client/package-lock.json
extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Confirmed by uncommenting the Disabled test get the stack trace
```
Suppressed: java.lang.NullPointerException: Cannot invoke "org.apache.myfaces.push.cdi.WebsocketScopeManager$AbstractScope.isChannelAvailable(String)" because the return value of "org.apache.myfaces.push.cdi.WebsocketScopeManager.getScope(String, boolean)" is null
at org.apache.myfaces.push.WebsocketComponentRenderer.encodeEnd(WebsocketComponentRenderer.java:148)
at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:634)
at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:523)
at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
at …
```

MYFACES-4684: 4.1 WebSocket integration test

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

MYFACES-4684: 5.0 Quarkus register websocket scopes

MYFACES-4684: 5.0 Quarkus register websocket scopes

---

impl/src/main/java/org/apache/myfaces/push/cdi/PushContextImpl.java

https://issues.apache.org/jira/browse/MYFACES-4680
TCK uses a viewscoped bean (not app scoped), and I'm assuming that  since app scope is null, it returns an empty collection. 
MYFACES-4680 still needs more work because a JavaScript error occurs: 
```
"makeException@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2496:16
assertFormExists@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2633:19
getForm@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2554:25
resolveForm@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development: …
```

MYFACES-4680

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/util/Lang.ts

Client side fix, adding the latest js code to the merge request

https://issues.apache.org/jira/browse/MYFACES-4680:

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java

Waiting to hear back if the user discovers any others.

MYFACES-4688: 5.0 Quarkus reflection/serialization

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/FacesUberJarProcessor.java

```
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.myfaces.core:myfaces-impl::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-impl\4.0.2\myfaces-impl-4.0.2.jar;], org.apache.myfaces.core:myfaces-api::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-api\4.0.2\myfaces-api-4.0.2.jar;]] contain duplicate files, e.g. META-INF/myfaces-metadata.xml
```

MYFACES-4427: 4.0 Quarkus UberJar add META-INF/myfaces-metadata.xml

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/FacesUberJarProcessor.java

```
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.myfaces.core:myfaces-impl::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-impl\4.0.2\myfaces-impl-4.0.2.jar;], org.apache.myfaces.core:myfaces-api::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-api\4.0.2\myfaces-api-4.0.2.jar;]] contain duplicate files, e.g. META-INF/myfaces-metadata.xml
```

MYFACES-4427: 5.0 Quarkus UberJar add META-INF/myfaces-metadata.xml

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/FacesUberJarProcessor.java

```
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.myfaces.core:myfaces-impl::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-impl\4.0.2\myfaces-impl-4.0.2.jar;], org.apache.myfaces.core:myfaces-api::jar:4.0.2[paths: C:\Users\melloware\.m2\repository\org\apache\myfaces\core\myfaces-api\4.0.2\myfaces-api-4.0.2.jar;]] contain duplicate files, e.g. META-INF/myfaces-metadata.xml
```

MYFACES-4427: 4.1 Quarkus UberJar add META-INF/myfaces-metadata.xml

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/FacesUberJarProcessor.java
extensions/quarkus/runtime/src/main/resources/META-INF/faces-config.xml

MYFACES-4427: 4.1 Quarkus UberJar check multiple classloaders for XML

---

extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/FacesUberJarProcessor.java
extensions/quarkus/runtime/src/main/resources/META-INF/faces-config.xml

MYFACES-4427: 5.0 Quarkus UberJar check multiple classloaders for XML

---

api/src/main/javascript/META-INF/resources/myfaces/_impl/quirks/_AjaxResponseQuirks.js

Fix for non webkit browsers in the quirks code

https://issues.apache.org/jira/browse/MYFACES-4685:

---

api/pom.xml
api/src/main/java/jakarta/faces/component/ActionSource.java
api/src/main/java/jakarta/faces/component/ActionSource2.java
impl/pom.xml
parent/pom.xml

Just syncing up with 4.1, but I know we'll clean this up later on.

Fix Myfaces 4692: ActionSource / ActionSource2 API  [5.0]

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/core/Const.ts
api/src/client/typescript/faces/impl/util/ExtDomQuery.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/util/ExtDomQueryTest.spec.ts
api/src/client/typescript/faces/test/myfaces/OamSubmit.spec.ts
api/src/client/typescript/faces/test/xhrCore/ErrorChainTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/XhrRequestProgress.spec.ts

Fixes
https://issues.apache.org/jira/browse/MYFACES-4676,
https://issues.apache.org/jira/browse/MYFACES-4691
And adds
https://github.com/werpu/jsfs_js_ts/issues/52:
A non intrusive extension which adds upload percentage tracking capabilities, per request of Tobago!

4.0.x: Various JS fixes (see description)

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/AjaxImpl.ts
api/src/client/typescript/faces/impl/core/Const.ts
api/src/client/typescript/faces/impl/util/ExtDomQuery.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/impl/util/ExtDomQueryTest.spec.ts
api/src/client/typescript/faces/test/myfaces/OamSubmit.spec.ts
api/src/client/typescript/faces/test/xhrCore/ErrorChainTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/EventTests.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest_23.spec.ts
api/src/client/typescript/faces/test/xhrCore/ResponseTest.spec.ts
api/src/client/typescript/faces/test/xhrCore/XhrRequestProgress.spec.ts

Fixes
https://issues.apache.org/jira/browse/MYFACES-4676,
https://issues.apache.org/jira/browse/MYFACES-4691
And adds
https://github.com/werpu/jsfs_js_ts/issues/52:
A non intrusive extension which adds upload percentage tracking capabilities, per request of Tobago!

4.1.x: Various js codebase fixes (see description)

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/@types/definitions/index.d.ts
api/src/client/typescript/faces/impl/xhrCore/ErrorData.ts
api/src/client/typescript/faces/impl/xhrCore/EventData.ts
api/src/client/typescript/faces/test/xhrCore/RequestTest_23.spec.ts

Fix for responseCode type
(cherry picked from commit 26b99369a4abc0cfa193b8d8cb32ac87b93c79b3)

https://issues.apache.org/jira/browse/MYFACES-4699:

---

impl/src/main/java/org/apache/myfaces/application/ResourceHandlerImpl.java

@tandraschko here is what I came up with please review

MYFACES-4696: 5.0 Undertow connection abort handling

---

.asf.yaml

.asf.yml for myfaces core for autolinking with jira

MYFACES-4702

---

impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java
impl/src/main/java/org/apache/myfaces/cdi/JsfArtifactProducer.java
impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
shared/src/main/java/org/apache/myfaces/shared/application/FacesServletMappingUtils.java

https://issues.apache.org/jira/browse/MYFACES-4705

[3.0] MYFACES-4705

---

api/src/client/package-lock.json
api/src/client/package.json
api/src/client/typescript/faces/impl/xhrCore/EventData.ts
api/src/client/typescript/faces/impl/xhrCore/ResponseProcessor.ts
api/src/client/typescript/faces/impl/xhrCore/XhrRequest.ts
api/src/client/typescript/faces/test/xhrCore/EventTests.spec.ts

(cherry picked from commit 3d3c50506fcbf2553126dbecadd309d9ccb1bd25)

https://issues.apache.org/jira/browse/MYFACES-4712: Fix and test

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java

I made the _autoCompleteOffViewState variable a String instead to support `one-time-code`. 
Also changed the default value back to true (as it before prior).
This also presents an issue where AUTOCOMPLETE_OFF_VIEW_STATE isn't an appropriate name anymore since it supports a new value. 
However, to avoid regressions or adding new context parameters, I think we can let this pass?

[2.3.x] Add one-time-code support to AUTOCOMPLETE_OFF_VIEW_STATE

---

api/src/client/package-lock.json
api/src/client/package.json

https://issues.apache.org/jira/browse/MYFACES-4723

---

impl/src/main/java/org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.java
impl/src/main/java/org/apache/myfaces/renderkit/html/util/AjaxScriptBuilder.java

fix for swallowed event type in command script

https://issues.apache.org/jira/browse/MYFACES-4719
